<template>
  <div class="relative overflow-x-auto py-8">
    <!-- Background Image -->
    <div class="absolute inset-0 z-0 flex items-center justify-center opacity-10">
      <img src="images/alflogo.png" alt="Logo" class="w-1/4 max-w-xs mx-auto" />
    </div>

    <!-- Table Content -->
    <div class="relative z-10">
      <table class="table-auto w-full max-w-7xl mx-auto border-collapse">
        <thead class="bg-official-purple-800 text-white">
          <tr>
            <th
              colspan="3"
              class="px-4 py-4 text-lg sm:text-xl md:text-2xl lg:text-3xl font-bold text-center uppercase tracking-wide"
            >
              The 2020-21 Bar Examinations Passers
            </th>
          </tr>
          <tr>
            <th
              colspan="3"
              class="px-4 py-4 text-lg sm:text-xl font-bold text-center bg-official-purple-700"
            >
              Hail to the 722 New Arellano Lawyers!
            </th>
          </tr>
        </thead>
        <tbody class="divide-y divide-gray-200">
          <!-- The Excellent Passer -->
          <tr class="bg-gradient-to-r from-yellow-50 to-amber-50">
            <td colspan="3" class="px-6 py-8 text-center border-b-2 border-amber-200">
              <div class="space-y-3">
                <div class="text-xs uppercase tracking-wider text-amber-600 font-semibold">The Excellent Passer</div>
                <div class="text-2xl md:text-3xl font-bold text-amber-800">Fernando Felix L. Imperial</div>
              </div>
            </td>
          </tr>

          <!-- The 39 Exemplary Passers Header -->
          <tr class="bg-gradient-to-r from-purple-50 to-indigo-50">
            <td colspan="3" class="px-6 py-4 text-center">
              <div class="text-lg font-bold text-purple-800 uppercase tracking-wide">
                The 39 Exemplary Passers
              </div>
            </td>
          </tr>

          <!-- Exemplary Passers in 3 Columns -->
          <tr v-for="(row, rowIndex) in exemplaryMaxRows" :key="'exemplary-' + rowIndex" class="flex flex-wrap md:table-row bg-purple-25">
            <td
              v-for="(column, colIndex) in exemplaryColumns"
              :key="colIndex"
              class="w-full px-6 py-3 text-sm leading-6 text-purple-900 md:w-auto text-left md:text-left font-semibold"
            >
              {{ column[rowIndex] || '' }}
            </td>
          </tr>

          <!-- The 722 New Arellano Lawyers Header -->
          <tr class="bg-gradient-to-r from-blue-50 to-cyan-50">
            <td colspan="3" class="px-6 py-4 text-center">
              <div class="text-lg font-bold text-blue-800 uppercase tracking-wide">
                The 722 Arellano Lawyers
              </div>
            </td>
          </tr>

          <!-- Regular Passers in 3 Columns -->
          <tr v-for="(row, rowIndex) in regularMaxRows" :key="'regular-' + rowIndex" class="flex flex-wrap md:table-row">
            <td
              v-for="(column, colIndex) in regularColumns"
              :key="colIndex"
              class="w-full px-6 py-3 text-sm leading-6 text-gray-800 md:w-auto text-left md:text-left hover:bg-gray-50 transition-colors"
            >
              {{ column[rowIndex] || '' }}
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

<script setup>
import { ref, computed } from "vue";

// The Excellent Passer
const excellentPasser = "Fernando Felix L. Imperial";

// The 39 Exemplary Passers
const exemplaryPassers = [
  "ALVAÑIZ, Anjo A.",
  "BALTAZAR, Mary Anne Micah R.",
  "BATULA-NASIAD, Kimberlyn S.",
  "BELLEN, Honey Joy M.",
  "CABAUATAN, Androus Rogel C.",
  "CARIAGA, Clive Hendelson F.",
  "CASTILLO, Charlotte Grace V.",
  "CAYAGO, Fresnel A.",
  "CAYANAN, Jennelyn J.",
  "DE ASIS, Francis M.",
  "LACANDALO, Justo Franco R.",
  "LAPUZ, Joyce S.",
  "LASAM, Clarence M.",
  "LIANGCO, Adrian Paul P.",
  "LOPERA, Joseph Gary Anthony L.",
  "MAGUMUN, Valeriano E.",
  "MANALILI, Mart Joel P.",
  "MANIO, Glenn J.",
  "MIGUEL, Gene Michael T.",
  "MONTES, Vincent N.",
  "NAMOCA, Daniella A.",
  "NASIS, Jovelyn T.",
  "NATIVIDAD, Paolo Miguel S.",
  "NOVIO, Virgilio IV T.",
  "ONG, Paolo Montano M.",
  "PATACSIL, Romel C.",
  "PIÑEDA, Ma. Anna Cecilia S.",
  "PINGOL, Jefferson M.",
  "QUIMSON, Jan Florenz M.",
  "QUINTOS, Roberto Octavo D.",
  "REYES, Earl James G.",
  "RIPA, Ana Mae M.",
  "SAMSON, Neil Emerson B.",
  "TAGAROMA, Joahanna G.",
  "TAMAYO, John Lester V.",
  "TAMAYO, Michael Angelo G.",
  "TAPOC, Enn Arr A.",
  "TIMPUG, Lyndon G.",
  "URQUICO, Roxanne S."
];

// Regular passers (excluding exemplary passers and excellent passer)
const allNames = [
  "ABASTA, Benazir Faye V.",
  "ABAYA, Floravick Ana B.",
  "ABDILLAH, Aliamen B.",
  "ABDULLAH-ALAUYA, Nishar Fatimah O.",
  "ABELLONAR, Christian A.",
  "ABRAZALDO, Romarie L.",
  "ABROGUEÑA, Clarisse Jhil A.",
  "ABUGO, Ariane Crystal Vine D.",
  "ABUYO, Jan Cedrik S.",
  "ACERON, April V.",
  "ACOSTA, Voltaire S.",
  "ADRIANO, Glaesan G.",
  "ADRIATICO, Paul Julius H.",
  "AGCARAO, Ma. Stephanie Faye O.",
  "AGTARAP, Alexis S.",
  "AGUBA-DOSPUEBLOS, Maria Abigail R.",
  "AGUILAR, Charles Tito R.",
  "AGUILAR, Jeross R.",
  "AGUINALDO, May Kristel D.",
  "AGUIRRE, Danica B.",
  "AGUSTIN, April Rose A.",
  "AGUSTIN, Gerald Archie M.",
  "ALAGOS, Dianne Kriza Wan Mae A.",
  "ALARCON, Maria Teresa L.",
  "ALARVA, Queen Marilyd S.",
  "ALAUYA, Amiruzzaman M.",
  "ALBERTO, Victoria Raye P.",
  "ALCASABAS, Jan Carolyn D.",
  "ALFONSO, Cornelio III Y.",
  "ALIGNO, Diego Salvador R.",
  "ALIM, Erica Paula L.",
  "ALMEDA, George D.",
  "ALMOGELA, Winona Audrey S.",
  "ALPAJORA, Diana Joy N.",
  "AMAC, Zoe Bryce T.",
  "AMAN, Abigail Joy L.",
  "AMBAS, Katrina Marie D.",
  "AMOLATO, Regine B.",
  "AMOR, Rutherford V.",
  "AMPATIN, Marcel Faith H.",
  "ANCIRO, Suzette A.",
  "ANTALAN, Charis S.",
  "ANTE, Jenneelyn Marie R.",
  "ANTEPASADO, Sherlaine Ann L.",
  "ANTIQUERA, Reigner Jireh D.",
  "AQUINO, Ernell Matthew S.",
  "ARADA, Beatriz Nicole A.",
  "ARCILLA, Arjan Jay Arsol D.",
  "ARELLANO, Eddie I.",
  "ARENA, Reil Jenily B.",
  "ARENAJE, Elaine M.",
  "ARISTON, Aaron Niegel R.",
  "ARNADO, Sheila Mae S.",
  "ARROYO, Kenneth C.",
  "ASAN, Samuel C.",
  "ASUNCION, Arthur D.",
  "ATIENZA, Donnalene Jane A.",
  "ATIENZA, Mark Cholo V.",
  "AUSTRIA, Caren W.",
  "AVECILLA, Ma. Concepcion L.",
  "AVEO, Erliza E.",
  "AVILES, Alyssa R.",
  "AZURO, Kristine Mary Ann C.",
  "BABIANO, Eloisa -",
  "BACAY, Florence Reneé R.",
  "BACURIO, Kenneth Bernard N.",
  "BALCUEVA, Ira Colleen E.",
  "BALDOVINO, Christian S.",
  "BALINDAN, Jarvish F.",
  "BALITA, Fatima Dexie D.",
  "BALUYOT, Gerald Francis C.",
  "BANLAYGAS, Castelo T.",
  "BAQUIRAN, Florencio Jr. C.",
  "BARNACHEA, Daniel Philip V.",
  "BARON, Marianne A.",
  "BARRANTES, Ezra C.",
  "BARTOLOME, Ralph Jireh A.",
  "BATTUNG, Marieflor S.",
  "BATULA, Daniel Dominic C.",
  "BAUTISTA, Carl steven B.",
  "BAUTISTA, Charles Aames M.",
  "BAUTISTA, Patrick L.",
  "BAWALAN, Allana Marie P.",
  "BAYABAO, April Z.",
  "BAYSA, Lynk Juren U.",
  "BEJER, Analyn B.",
  "BEJOSANO, Jose Ibarra D.",
  "BELARDE, Kevin Shawn Ray S.",
  "BELARMINO, Aliza L.",
  "BELDAD, Mary Bernadette L.",
  "BELISTA, Charisa L.",
  "BELTRAN, Enrique A.",
  "BELTRAN, Mark Salvador C.",
  "BELTRAN, Patricia Bianca E.",
  "BENITEZ, Paula Diane",
  "BERNALES, Maybelle Joy E.",
  "BERNARDO, Angelica A.",
  "BERNARDO, Harold M.",
  "BERNARDO, Mary Chelean Michelle L.",
  "BIGAY, Donnabelle S.",
  "BINALAY, Carol P.",
  "BO, Raoul Isagani Jr. R.",
  "BOBILES, Francis Mico E.",
  "BOCALAN, Mary Danielle E.",
  "BOCO, Eva Joy C.",
  "BOÑAGA, Charina Mae B.",
  "BONAOBRA, Rose Ann B.",
  "BONEO, Jico V.",
  "BORILLO, Koreen C.",
  "BORJA, Merryl Angelic C.",
  "BOTOR, Maria Agnes R.",
  "BRAVO, Francisco Jr. O.",
  "BRICIA, Jan Karlo V.",
  "BRIONES, John Caldan P.",
  "BRITANICO, Nerie D.",
  "BROZO, Mark James M.",
  "BUENCONSEJO, Ahreen Kiela B.",
  "BUENO, Johnrom Homer M.",
  "BUGTAS, Camille C.",
  "BUMANLAG, Leida Mae L.",
  "BUNGUBUNG, Pia Christine M.",
  "BURCE, Ernie A.",
  "BUSA, Natividad G.",
  "BUSOG, Jones Harold Bird M.",
  "CABALANG, Alyssa Faye P.",
  "CABANAG, Jose Antonio S.",
  "CABELLO, Mia Margaritha T.",
  "CABIAS, Dome Myrll T.",
  "CABRAL, Alyanna Angelina M.",
  "CABUHAT, Milea Kim Karla S.",
  "CABUS, Theodore L.",
  "CADAVOS, Mae Ann M.",
  "CADIZ, Karl Andrei N.",
  "CAI, Michael Kean L.",
  "CAISIP, Marlon M.",
  "CALACA, Shaliha Anjierah R.",
  "CALIUAG, Jordanne Marie B.",
  "CALIWARA, Lester Joseph L.",
  "CANONIZADO, Jenny Kenn S.",
  "CANOSA, Ezra Joy A.",
  "CANTORIA, Gianna B.",
  "CAOAGDAN, Marlou S.",
  "CAPA, Kristabelle T.",
  "CAPARIÑO, Joselito Narciso B.",
  "CAPURCOS, Jumel L.",
  "CASAR, Hyderabad R.",
  "CASIMERO, Mark Almund M.",
  "CASTILLO, Frances Gail F.",
  "CASTILLO, Nina Beleen F.",
  "CASTRO, Emir M.",
  "CATALAN, Rachel Ann P.",
  "CATIMBANG, Christine C.",
  "CATIPAY, Jan Kriezl M.",
  "CATUBAY, Nica A.",
  "CAZEÑAS, Vanessa Gem P.",
  "CERACAS, Paula Mae Y.",
  "CHAN, Vien Lenox C.",
  "CHUA, Glenn D.",
  "CHUA, Janica Joyce D.",
  "CIAR-REMIGIO, Julie Anne Princess A.",
  "CLAUDIO, Ma. Judith A.",
  "CLAVERIA, Carina Amor D.",
  "CLEMENTE, Jerick Angelo D.",
  "CLEMENTE, Lisa Marie J.",
  "CLEOFE, Mark Jeff V.",
  "CLUTARIO, Jumar A.",
  "COMALING, Abigail B.",
  "COMON, Dianne G.",
  "CONDES, Reyna Amor R.",
  "CORONADO, Jeffrey A.",
  "CORONEL, Nikki Manuel S.",
  "CORPUZ, Maria Christina F.",
  "CORTEZ, Elizabeth Joy D.",
  "CRUZ, Aura Jeune F.",
  "CRUZ, Glen Johannes P.",
  "CRUZ, Kerwin A.",
  "CRUZ, Mikka J.",
  "CUARTERO, Laisa Marie D.",
  "CUERDO, April Joy A.",
  "CUEVAS, Charmagne L.",
  "CUSTODIO, Ness Ivy C.",
  "CUSTODIO, Shiela Arman B.",
  "DALISAY, Reynaldo Jr. S.",
  "DAVID, Kremil S.",
  "DAYANGHIRANG, Emilio IV A.",
  "DAYAO, Ernesto Jr. N.",
  "DAYRIT, Jeselle Anne V.",
  "DE ASA, Christian Allen A.",
  "DE BELEN, Annelyn G.",
  "DE CASTRO, Fritz Angelain R.",
  "DE GUZMAN, Daisy Diane A.",
  "DE GUZMAN, Gian C.",
  "DE GUZMAN, Joey Albert P.",
  "DE JESUS, James Nicol D.",
  "DE LA CRUZ, Babylyn C.",
  "DE LEON, Inna Elyjah Beatrice C.",
  "DE LEON, Nathaniel C.",
  "DE LOS SANTOS, Stephen Reymar V.",
  "DE PAZ, Mary Athena D.",
  "DE VERA, Josef Paul L.",
  "DEDACE, Carl Ericson John R.",
  "DEL ROSARIO-GELACIO, Eunice P.",
  "DEL ROSARIO, William Jr. C.",
  "DELA CRUZ, Harriz F.",
  "DELA CRUZ, Juan Pepito E.",
  "DELA CRUZ, Raquel M.",
  "DELA PEÑA, Yndrei P.",
  "DELA REA, Steve Jr. B.",
  "DELA VEGA, Alexis D.",
  "DESAMPARADO, Alexandra T.",
  "DESCARTIN, Justin Jeremy Edrei B.",
  "DIAGAO, Jiehan A.",
  "DIAMANTE, Ma. Kristina B.",
  "DIANALAN, Abdul Azis IV D.",
  "DIGNADICE-VILLAFLOR, Ethel Hope L.",
  "DIMAAMPAO, Mohammad F.",
  "DIMALOTANG, Sapphira T.",
  "DINEROS, Lady Lyn D.",
  "DINGLASAN, Wendel C.",
  "DIONISIO, Lauren Gabrielle S.",
  "DIVINAGRACIA, Jay Ann E.",
  "DIWA II, Leonardo B.",
  "DIWA, Andrea Marciana B.",
  "DIZON, Enrique V B.",
  "DIZON, Hersan Ivan S.",
  "DIZON, Paolo John A.",
  "DIZON, Roi Christopher T.",
  "DOMANICO, Jake E.",
  "DORADO, Czaybeeh E.",
  "DOROJA, Patricia Agatha May B.",
  "DUMAUAL, Jeanne Pauline J.",
  "DUPAYA, Quinnie Anne V.",
  "ELAURIA, J. Paulo R.",
  "EMPLICA, Kevin TJ A.",
  "ENFECTANA, Jazzmin L.",
  "ENRIQUEZ, Francis Xavier N.",
  "ERANA, Zilpha Leah A.",
  "ERODIAS, Dominador III D.",
  "ESCARTIN, Stephen C.",
  "ESCOTO, Michael Paul A.",
  "ESPAÑOLA, Adrienne C.",
  "ESPINA, Kaye G.",
  "ESPINAS, Queen Therese D.",
  "ESPINOSA, Claudia Martina N.",
  "ESPINOSA, Maria Ana E.",
  "ESPIRITU, Nadine Xyra C.",
  "ESTEMBER, Daniel John G.",
  "EVANGELIO, Jasper Paul V.",
  "EVANGELISTA, Joann Ross C.",
  "FABIO, Mikhail Jude Amando III R.",
  "FABROS, Sarah Maria E.",
  "FAJARDO, Jheremiah M.",
  "FEDILLAGA, Glenn Robin C.",
  "FERAREN, Adrian P.",
  "FERNANDEZ, Jonah U.",
  "FERNANDO, Kristin Jomafer C.",
  "FLORES, Areeya M.",
  "FLORES, Aurelio Neil S.",
  "FLORES, Jaquelyn Mae O.",
  "FLORES, Joel F.",
  "FLORES, Joshua A.",
  "FLORES, Marie Elinor L.",
  "FLORES, Rochelle Rita Marie N.",
  "FLORES, Rommel Brian P.",
  "FONTANILLA, Miguel Luigi IV E.",
  "FORTICH, Ver Anthony A.",
  "FRANCISCO, Joseph O.",
  "FRESCO, Jordan",
  "GABATINO-QUERIDO, Maria Kritzel Christina C.",
  "GABI, Hershey F.",
  "GABO, Maria Joanna Dahlene A.",
  "GADIANE, Sam Jade M.",
  "GALANG, John Rosendo A.",
  "GALANO, Faith Alexis F.",
  "GALAPON, Kariene Gayle R.",
  "GALERA, Paul John B.",
  "GAMBOA, Joelyn Marie G.",
  "GARCIA-PASION, Joeanna Mhay D.",
  "GARCIA, Anne Sherina Bianca J.",
  "GARCIA, John Edward M.",
  "GARCIA, Justin Carlos N.",
  "GARCIA, Lawrence Felix T.",
  "GARCIA, Maria Angeles Imelda L.",
  "GARCIA, Maria Celine Elizabeth R.",
  "GARDE, Arnel Q.",
  "GARMA, Don Aehrjay S.",
  "GASTANES, Edmond Jones Q.",
  "GATCHALLAN, Jan Laurence G.",
  "GATUC, Ralph Lawrence B.",
  "GENERALAO, Leo Lorenz D.",
  "GIBA, Ronie Cris R.",
  "GLOVASA, Imelou A.",
  "GO, Denise Kimberly Krizelle D.",
  "GOBANTES, Primabelle S.",
  "GOBOLE, Mary Sarah D.",
  "GOLOD, Jeffrey C.",
  "GOMEZ, Jesus Angelo P.",
  "GONZALES, Irene A.",
  "GONZALES, Nomer M.",
  "GORDON, Francis Voltaire Y.",
  "GUEVARRA, Jyrna Rhea J.",
  "GUEVARRA, Karl Derrick S.",
  "GUIAM, Carlo R.",
  "GUILING, Aniesahara L.",
  "GUILLEN, Joseph Angelo J.",
  "GUILLERMO, Lingelie A.",
  "GUMABOL, Erika Mae U.",
  "HASSAN, Khalid A.",
  "HATAB, Karizsa A.",
  "HERNANDEZ, Leah G.",
  "HERNANDEZ, Mark Dondee L.",
  "HERNANDEZ, Penelope H.",
  "HERNANDEZ, Tyrone Carlo M.",
  "HERNANDO, Raymundo Francisco A.",
  "HICARO, Karen Joy P.",
  "HOLMAN, Edson Bill M.",
  "HOW, Sharrah Josse D.",
  "HUERTA, Juris U.",
  "IGLESIAS, Maria Katrinna M.",
  "ILAGAN, Juverglen C.",
  "ILAGAN, Richard E.",
  "INFANTADO-TAGUIBAO, Ciara Christia P.",
  "ISMAEL, Jimlan S.",
  "JACINTO, Doane Kevin P.",
  "JAMERO, Gari R.",
  "JAMPAS, Joseph Marwin B.",
  "JAVIER, Imee Joy B.",
  "JIMENA-PEREZ, Janine B.",
  "JOCSON-TAN, Jacelud A.",
  "JOQUIÑO, Nathaniel S.",
  "JOSUE, Aileen Joy A.",
  "JOYA, Donald Jude H.",
  "JOYAS, Victor Emmanuel C.",
  "JUBA, Jereca U.",
  "JUMAGDAO, Chrismaire D.",
  "JUMALON, Erika B.",
  "JURADO, Aldritz Ignacio III P.",
  "KINDIPAN, Kathleen P.",
  "KING, Daniel M.",
  "KIONG, Shaira Kasey L.",
  "KOK, Katrisha Analine B.",
  "KUA, Teresa Katherine R.",
  "LA MADRID, Rafael Andrei U.",
  "LABORDO, Aaron Anthony S.",
  "LADJAHASAN-LAS, Zainab W.",
  "LAGUITAO, Judith Z.",
  "LANCION, Rolan Jeff A.",
  "LANTAKA, Grace Katherine M.",
  "LARA, Jengke F.",
  "LARA, Kristina A.",
  "LARIN, Janusz Paolo G.",
  "LASALA, Shantee S.",
  "LAURENTE, Krisha Mae M.",
  "LAURIO, Izza Mari D.",
  "LAVARES, Marc Ronald N.",
  "LAYGO, Mark Dann S.",
  "LEDESMA, Ma. Thea Lynn G.",
  "LEE, Christian Gerard G.",
  "LEE, Ivan Jan G.",
  "LEGASPI, Jaypee A.",
  "LEONES, Carl Jerry E.",
  "LEYVA, Mary Ann H.",
  "LIM-TAN, Joan H.",
  "LIM, Anton Kristoffer M.",
  "LIM, John Marc I.",
  "LIM, Mark Chester S.",
  "LIMBOC, Alyssa Anne Bernadette J.",
  "LINCOD, Daryl D.",
  "LINDA, Karen Claudine M.",
  "LIRIO, Christopher T.",
  "LISING, Paula F.",
  "LOBRIGO, Niña Therese L.",
  "LONGOS, Victor C.",
  "LOPEZ, Laura P.",
  "LOYOLA, Paula Bianca A.",
  "LOZADA, Wenceslao Georgio U.",
  "LOZANO, Doel B.",
  "LUBANGCO, Marc Russel Ann P.",
  "LUCIANO, Romena R.",
  "LUMANLAN, Rolinda G.",
  "LUZADAS, Regina Rae G.",
  "MAAT, Kimberly Mae S.",
  "MACABABBAD, Realyn T.",
  "MACAPAGAL, Divine Jomarie R.",
  "MACATANGAY, Ren Irene D.",
  "MADELO, Ginalyn G.",
  "MADLAMBAYAN, Isaiah Gil L.",
  "MAGADA, Jeffrey M.",
  "MAGALLANES, Van John C.",
  "MAGISA, Odessa Rossilyz L.",
  "MAGISTRADO, Emmanuel B.",
  "MAGLAYA, Guillermo III S.",
  "MAGNO, Alfredo Marcos C.",
  "MAGSANO, Ma. Cristina Rae E.",
  "MAGSINO, Jamaica B.",
  "MAGSUMBOL, Guiller C.",
  "MALABANAN, Jaymond Jorge H.",
  "MALALUAN-CRUZ, Ria M.",
  "MALIJAN, Gerani D.",
  "MALLARI, Peter Anthony T.",
  "MAMANGON, Fatima C.",
  "MAMAUAG, Florenz Gabriel S.",
  "MANAHAN, Eurice Anne C.",
  "MANCENIDO, Mach Jefferson S.",
  "MANDA, Loren Marie B.",
  "MANGAHAS, Ma. Bianca D.",
  "MANGAYA, Francis Luigi R.",
  "MANGUNI, Jeanifer L.",
  "MANIGBAS, Joyce D.",
  "MANIGBAS, Riztian Dale D.",
  "MANLONGAT, Artemio Gonzalo A.",
  "MANLULU, Rudolfh Kevin A.",
  "MANOTOK, Leah Christianilde F.",
  "MANZANO, Aimee Rose L.",
  "MAQUIRAYA, Mark Gregory R.",
  "MARANGA, Mark Gabriel B.",
  "MARCELO, Trisha Mae A.",
  "MARCELO, Trixie A.",
  "MARILIM, Edgar John O.",
  "MARIÑAS, Maria Pacita M.",
  "MARIQUINA, Eva Marie C.",
  "MARQUEZ, Jay Michael A.",
  "MARZAN, Jeffrey O.",
  "MASCARIÑAS, Hazel H.",
  "MATANOG, Norhanifa B.",
  "MATEO, Mark Anthony T.",
  "MATIAS, Michelle Dulce C.",
  "MATIBAG, Lorenzo V.",
  "MATIENZO, Maricris P.",
  "MEDIAVILLO, Ronel L.",
  "MEDINA, Doris Marie M.",
  "MEJICA, John Paolo A.",
  "MELCHOR, Lyndon Pedro Jay Jr. B.",
  "MENDOZA, Angelica P.",
  "MENDOZA, Barleon R.",
  "MENDOZA, Christine Joyce S.",
  "MENDOZA, Criselda Buhay P.",
  "MENDOZA, Mia Cielo P.",
  "MENESES, Rosendo IV D.",
  "MENGULLO, Teneessee Anne L.",
  "MENZON, Romualdo Jr. A.",
  "MERGAS, Krema Jean C.",
  "MIÑOZA, Shawn Michael P.",
  "MIRANO, Erlyn E.",
  "MIRHAN, Jaime Mathew R.",
  "MISOLA, Mark Gil E.",
  "MOJARES, Mae Antonette L.",
  "MOLINO, Vanessa Marie C.",
  "MONCUPA, Bernadette J.",
  "MONTANCES, Jane Mabel F.",
  "MONTAÑO, Ram Richsmart V.",
  "MONTEVERDE, Angelo Seigfreid S.",
  "MONTOYA-PARAGAS, Shiela-ann R.",
  "MONTOYA, Jacques Evan M.",
  "MORAGA, Clarissa G.",
  "MORALEJO, Donald Jay E.",
  "MORALES, Patrick Jay F.",
  "MUNGCAL, Joanna Krystle",
  "MUNIEZA Jr., Godofredo T.",
  "MURIA, Nadja Valerie M.",
  "NACA, Angelica Marie S.",
  "NACILLA, Nica Jenine O.",
  "NACPIL, Gerald L.",
  "NAPAY, Joan Don A.",
  "NATIAL, Aldrin James N.",
  "NAVARRO, Ezekiel Demetrio J.",
  "NAVARRO, Rafael Christian S.",
  "NEGAPATAN, Art Ryan P.",
  "NIFAS, Gabriel Vincent G.",
  "NOVENO, Kathlene D.",
  "NUGAL, Celeste Marie R.",
  "OCAMPO, Jaden B.",
  "OCAMPO, Maria Teresa Ann R.",
  "ODSINADA, Herbert R.",
  "OGAYON, Ralph Vincent M.",
  "OINEZA, Jonathan Tomas D.",
  "OLALIA, Erikson Q.",
  "OLIVEROS, Jeffrey B.",
  "ORALLO, Rene II C.",
  "ORTEGA, Marni Fenina F.",
  "ORTIZ, Maria Theresa J.",
  "ORTIZ-JALAPA, Diana A.",
  "OSIAL, Rolindo Fausto A.",
  "OSINGAT, Efraim C.",
  "PABLO, Xavier C.",
  "PACAMALAN, Dirika D.",
  "PACASUM, Aljohn S.",
  "PACHECO, Jose Acerey Jr. M.",
  "PADERAYON, Katrina Alyanna G.",
  "PAESTE, Lybenson B.",
  "PAGENTE, Jigg Lynnard B.",
  "PAGLINAWAN, Al Mayo Sandino C.",
  "PALMA, Karen Clarisse P.",
  "PALOMO, Ronna Athena A.",
  "PANGANIBAN, Shanna Mae L.",
  "PANO, Gretchen R.",
  "PANTOÑAL, Cynthia V.",
  "PARADO, Ma. Angela Pia P.",
  "PARULAN, Kathleen A.",
  "PARUNGAO, Andrew James F.",
  "PASCUA, Joanna B.",
  "PASCUA, Rownelee G.",
  "PASION-GOLBERG, Sandra T.",
  "PASTORES, Kristine P.",
  "PATRICIO, Aira Joyce G.",
  "PEDRAJAS, Charlene T.",
  "PELAYO, Rossenee D.",
  "PEÑAFLOR, Alexander P.",
  "PENOLIO, John Michael N.",
  "PENUS, Marc Kenneth J.",
  "PEREÑA, Ryan Anthony G.",
  "PEREZ, Florabelle A.",
  "PERLEZ, Dezery M.",
  "PIANSAY, Joanna Christine A.",
  "PILIMPINAS, Mary Lorenz C.",
  "PINCA, Jana Paola E.",
  "PINEDA, Christine Sharmaine M.",
  "PINEDA, Maica P.",
  "PION, Paola Margarita V.",
  "PLOMILLO, Rea Chill C.",
  "POBRE, Ralph Vincent A.",
  "POCOT, Eldan R.",
  "POLANGCOS, Maui F.",
  "POLINES, Jonas G.",
  "PRADES, Michaela B.",
  "PUA, Ma. Angelie Erika V.",
  "PULIDO, Angelica R.",
  "PUSPUS, Eden P.",
  "QUEBEC, Ralph M.",
  "QUIMADO, Julie Antonette B.",
  "QUIÑONES, Shirley Marie C.",
  "QUIZON, Kaye Antonette B.",
  "QUIZZAGAN, Micah B.",
  "RABADON, Karen Joy M.",
  "RAFAEL, Romm Albert D.",
  "RAGUINDIN, Joy Ann N.",
  "RAMALLOSA, Hannah Kamille E.",
  "RAMARAMA, Joseph Nico P.",
  "RAMIL, Mark Erick C.",
  "RAMIREZ, Edna C.",
  "RAMIREZ, Rey Rhymyl",
  "RAMIREZ, Romeo Jr. D.",
  "RAMOS, Angelica Crisgar B.",
  "RAMOS, Bryan Angelo D.",
  "RAYOSO, Sunshine U.",
  "REAS-GARIN, Emyrose R.",
  "RECIO, Nikki Dianne S.",
  "RED, Revo Joshua R.",
  "REINTAR, Ely Jr. Z.",
  "RELATIVO, Janielle Anne D.",
  "RESURRECCION, Leandro Jose Antonio IV C.",
  "RESURRECCION, Rexford C.",
  "REYES, Clariza A.",
  "REYES, Frances Gabrielle C.",
  "REYES, Kristoffer C.",
  "REYES, Luigi T.",
  "REYES, Toni Patricia May S.",
  "RICALDE, Marra Antonnette L.",
  "RIGOR, Karla Michaela J.",
  "RIVERA, Novelyn B.",
  "RIVERA, Paul Joshua M.",
  "RIVERO, Julius Bien L.",
  "ROBLES, Voltaire R.",
  "ROMANO, Harvey Leo M.",
  "ROMERO, Leo Ernesto Thomas G.",
  "ROSAL, Cheerly P.",
  "ROSERO, Celso III M.",
  "ROXAS, Hazel P.",
  "RUALO, Ann Mary Michelle B.",
  "RUIZ, Kimberly Joy A.",
  "SAAVEDRA, Anne Janine M.",
  "SAGMON, Kristine Joanne T.",
  "SAGUN, Justin Robert F.",
  "SALAPARE, Justin Earl Daryll P.",
  "SALAS, Paula Blanca B.",
  "SALAZAR, Marion Joseph Z.",
  "SALDO, Maria Luisa N.",
  "SALMASAN, Ivan Japeth V.",
  "SALVADOR, Antonio Dominic G.",
  "SALVANI, Raizza Dawn B.",
  "SAMSON, Ivan Bernard T.",
  "SAMSON, Jhelisa R.",
  "SAN MATEO, Paolo T.",
  "SANCHEZ, Gonzalo Jr. S.",
  "SANCHEZ, Jan Carlo M.",
  "SANGALANG, Heriberto II C.",
  "SANGALANG, Shalena S.",
  "SANIANO, Jerome Bryan M.",
  "SANTELICES, Aila Nicko V.",
  "SANTIAGO, Lariela Camille S.",
  "SANTIAGO, Marielle D.",
  "SANTILLAN, Oscar Ryan M.",
  "SANTOS-BORJA, Justinne Marie D.",
  "SANTOS, Army P.",
  "SANTOS, Aura Eunice S.",
  "SANTOS, Erika Joy A.",
  "SARIP, Gani Jr. P.",
  "SARMIENTO, Majesca M.",
  "SATUITO, Miguel Angelo D.",
  "SAYAO, Melissa Ezra B.",
  "SEBRIO, Mikhail C.",
  "SEEBOK, Jonathan L.",
  "SEÑA, Mark Andrew R.",
  "SENADOS, Nahum Jasmin M.",
  "SENDIN, Kring-kring",
  "SEÑERES, Roy Jr. M.",
  "SERRANO, John Kevin M.",
  "SIASOCO, Nehvin Reza",
  "SIDDAYAO, Janus G.",
  "SIM, Nowell Paolo Q.",
  "SISON, Aldous Francis P.",
  "SISON, Yolanda C.",
  "SO, Junalyn Gift C.",
  "STO TOMAS, Bay Ariel N.",
  "SULIT, Michelle Faye D.",
  "SY JUCO, Michelle E.",
  "SY, Angelo Bilton C.",
  "TABION, Juris Nicholo Gabriel B.",
  "TABIOS, Jeneve A.",
  "TAGALA, Mark Joseph T.",
  "TAGAYUNA, Carlo A.",
  "TALENS, Maria Celina M.",
  "TAMAYO, Jumen G.",
  "TAMBUT, Nurnien C.",
  "TAN, Arvi James R.",
  "TAN, Dominique Janzen C.",
  "TANGHAL, Noelle Christine P.",
  "TATAD, Jillian Monikah A.",
  "TEEPECUY, Maria Yvette Bernadette V.",
  "TEJARES, Anthony Angel S.",
  "TELLO, Thapten V.",
  "TERENCIO-SANTIAGO, Ma. Penelope T.",
  "TIAMA, Gemma F.",
  "TIBURAN, Jordan C.",
  "TIU, Hanz Darryl D.",
  "TOLENTINO, Joana Mariz F.",
  "TOLENTINO, Jonaselle F.",
  "TOLENTINO, Karen G.",
  "TOLENTINO, Ma. Angelica L.",
  "TORDIL, Ryan O.",
  "TORRALBA, Maurice George C.",
  "TORRES, Anderson D.",
  "TRINIDAD, Danica Floricia Mae D.",
  "TRINIDAD, Lizette A.",
  "TRISTEZA, Kristine F.",
  "TUGAS, Alvin Jan T.",
  "TULAUAN, Neil Jasper T.",
  "TULLO, Krissa Jennesca T.",
  "TUNAC, Ray Alvin F.",
  "TURARAY, Maria Jeminah B.",
  "TUTAAN, Simeon Jr. M.",
  "UNTALAN, Grace E.",
  "URAYENZA, Eva Joy S.",
  "URBIZTONDO, Vincent Czar C.",
  "UY-TIOCO, Kristine Joan M.",
  "UY, Rodolfo III D.",
  "VALENTON, Francis Angelo T.",
  "VARONA, Florescinda Mae N.",
  "VELASCO, Rim Mariel F.",
  "VELASCO, Sheryl C.",
  "VELAZCO, Erwin Joseph G.",
  "VELOSO, Jocelyn M.",
  "VENGCO, Allan Paolo B.",
  "VERGARA, Maria Ahren P.",
  "VILLABLAGON, Johnrey L.",
  "VILLALUNA-NAVALES, Annalyn G.",
  "VILLAMOR, Wilbert Gil III A.",
  "VILLANUEVA, Emilio Jan D.",
  "VILLANUEVA, Nanette Eloisa A.",
  "VILLAREAL, Jusel T.",
  "VILLAREAL, Marjorie D.",
  "VILLENA, Roxane Mae B.",
  "YALUNG, Ma. Danela Q.",
  "YAMBOT, Edson M.",
  "YANTO, Marienela M.",
  "YSULAN, Jenalyn M.",
  "YUSON, Angelica Mae P.",
  "ZABALA, Cariza May J.",
  "ZAGADA, Maureen D.",
  "ZIGA, Richard Venancio Fernando V."
];

// Remove exemplary passers from regular list to avoid duplicates
const regularPassers = allNames.filter(name => !exemplaryPassers.includes(name));

// Computed properties
const divideIntoColumns = (list, columnCount) => {
  const columns = Array.from({ length: columnCount }, () => []);
  list.forEach((name, index) => {
    columns[index % columnCount].push(name);
  });
  return columns;
};

// Exemplary passers (already sorted)
const exemplaryColumns = computed(() => divideIntoColumns(exemplaryPassers, 3));
const exemplaryMaxRows = computed(() => Math.max(...exemplaryColumns.value.map(col => col.length)));

// Regular passers (sorted)
const sortedRegularPassers = computed(() => [...regularPassers].sort((a, b) => a.localeCompare(b)));
const regularColumns = computed(() => divideIntoColumns(sortedRegularPassers.value, 3));
const regularMaxRows = computed(() => Math.max(...regularColumns.value.map(col => col.length)));
</script>