<template>
  <div class="relative overflow-x-auto py-8">
    <!-- Background Image -->
    <div class="absolute inset-0 z-0 flex items-center justify-center opacity-10">
      <img src="images/alflogo.png" alt="Logo" class="w-1/4 max-w-xs mx-auto" />
    </div>

    <!-- Table Content -->
    <div class="relative z-10">
      <table class="table-auto w-full max-w-7xl mx-auto border-collapse">
        <thead class="bg-official-purple-800 text-white">
          <tr>
            <th
              colspan="3"
              class="px-4 py-4 text-lg sm:text-xl md:text-2xl lg:text-3xl font-bold text-center uppercase tracking-wide"
            >
              The 2022 Bar Examinations Passers
            </th>
          </tr>
          <tr>
            <th
              colspan="3"
              class="px-4 py-4 text-lg sm:text-xl font-bold text-center bg-official-purple-700"
            >
              Hail to the 378 New Arellano Lawyers!
            </th>
          </tr>
        </thead>
        <tbody class="divide-y divide-gray-200">
          <!-- 20th Placer - Full Width Centered Row -->
          <tr class="bg-gradient-to-r from-blue-50 to-indigo-50">
            <td colspan="3" class="px-6 py-8 text-center border-b-2 border-blue-200">
              <div class="space-y-3">
                <div class="text-2xl md:text-3xl font-bold text-blue-800">Kyle Terence Amilao Villoria</div>
                <div class="text-lg font-semibold text-blue-600">20th Placer</div>
                <div class="text-sm text-blue-500 italic">(Examinees Who Obtained the Thirty Highest Ratings)</div>
              </div>
            </td>
          </tr>

          <!-- The 378 New Arellano Lawyers Header -->
          <tr class="bg-gradient-to-r from-purple-50 to-indigo-50">
            <td colspan="3" class="px-6 py-4 text-center">
              <div class="text-lg font-bold text-purple-800 uppercase tracking-wide">
                The 378 New Arellano Lawyers
              </div>
            </td>
          </tr>

          <!-- Regular Passers in 3 Columns -->
          <tr v-for="(row, rowIndex) in maxRows" :key="rowIndex" class="flex flex-wrap md:table-row">
            <td
              v-for="(column, colIndex) in columns"
              :key="colIndex"
              class="w-full px-6 py-3 text-sm leading-6 text-gray-800 md:w-auto text-left md:text-left hover:bg-gray-50 transition-colors"
            >
              {{ column[rowIndex] || '' }}
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

<script setup>
import { ref, computed } from "vue";

// Full list of names for 2022 Bar Passers (excluding the placer)
const allNames = [
  "ABADILLA, Jessica Carable",
  "ABALOS, Randel Sumaya",
  "ABAQUITA, Jose Carlo Alfonso Ladia",
  "ABCEDE, Aile Carissa Pamon",
  "ABENIO, Mary Gail Adal",
  "ABLAZA, Joshua Dale Abratigue",
  "ABOCADO, Marra Kristine Azores",
  "ABOY, Kevin Albert Cabili",
  "ADRAYAN, Stephen Michael Abogado",
  "ADRIANO, Myka Lacson",
  "ALAGAO, Elaine Mae Villeguez",
  "ALBANO, Mae-Dawn Giron",
  "ALCALA, Garry Barcebal",
  "ALCOVER, Helen Tinaja",
  "ALFONSO, Geonel Marko Pangilinan",
  "ALMAJOSE, Lilia Aurora Avendaño",
  "AMANTE, Calbert Dustin Legaspi",
  "ANDALAN, Riza Lopres",
  "ANDALECIO, John Dom Santillan",
  "ANENIAS, Frances Catherine De Torres",
  "APALE, Carl Justine Mauri",
  "AQUINO, Joanne Zoe Dazo",
  "ARAGON, Jyn Ebrada",
  "ARGOSINO, Julienne Acibar",
  "ASTIBE, Maria Jennifer Celestino",
  "ATIENZA, Earvin James Martinez",
  "AVETRIA, Ruby Ces",
  "AYON, Hanna Miranda",
  "AYTONA, Fiona Margarita Santos",
  "AÑONUEVO-BANAG, Liezel Ramirez",
  "BACARRO, Tracie Kathlynne Bonsato",
  "BACASER, Jimver Abadiano",
  "BADIOLA, Jose Victor Jallores",
  "BALAN, Kristen Roseljoy Cañada",
  "BALBIN, Allan Paul Bercasio",
  "BALITCHA, Rolf Agustin",
  "BALTAZAR, Mary Anne Christine Reyes",
  "BARCETA, Joselito Icawat",
  "BARENG, Kristian Nicole Mina",
  "BARRAMEDA, Raisa Serrano",
  "BARRAS, Cassy Canda",
  "BARRIOS, Bahttina Kim Mercado",
  "BARROGA, Iyra Joy Directo",
  "BARSABAL, Rizel Cuarteros",
  "BATO, Johaimen Monib",
  "BAULA, Irish Ann Turtor",
  "BAUTISTA, Arby Salorsano",
  "BAUTISTA, Neil Jopet Paña",
  "BAUTISTA, Renz Ramos",
  "BAYSA, Maiko Kaye Ubay",
  "BELANGEL, Carl Ted Borromeo",
  "BERLAN, Leniñeto Pomida",
  "BESID, John Evan Raymund Olaso",
  "BIDO, Roxanne Siervo",
  "BILBAO, Arwin Trono",
  "BILO, Joefranz Villar",
  "BONDOC, Jeric Mendoza",
  "BRANDEZ, Ricardo",
  "BRONDIAL, Sofia Monique Salvador",
  "BUCALAN, Amie Grace Buenaventura",
  "BUNAL, Mary Denzyll Reyes",
  "BURCE, Anna Liza Mercado",
  "CABREGA, Angelica Jardin",
  "CABUHAT JR., Romeo Osdaña",
  "CALACA, Norjanizah Airah Ramos",
  "CALALO, Shiela Regacho",
  "CALUSA, Catherine Loverez",
  "CAPARA, Jeanny Anne Natividad",
  "CARALDE, Reishajan Cañazares",
  "CARIÑO, Trudi Blas",
  "CASILANA, Krizzia Erika Peñaflor",
  "CASTILLO, Christen Domingo",
  "CASTRO, Dennis Lazobert Dizon",
  "CATALAN, Julia Anne Mari Reyes",
  "CELEDIO, Marvin Mabini",
  "CELLS, Maricris Ilagan",
  "CHAN, Erving Dominguez",
  "CHAN, Jayson Howard Cuysona",
  "CHIANPIAN, Crisanta Leonor Lee",
  "CHING, Marian Frenesi Javier",
  "CHUA, Al Anthony Mercado",
  "CIUDADANO, James Mark Padrones",
  "CLEMENCIA, Dana Mae Cuevas",
  "CLERINO, Paul Rhidel Talucod",
  "COLADA, Joanikka Mae Colada",
  "CONDE, Lovely Rose Yaput",
  "CORPUZ, Magdalena Calacday",
  "CUSTODIO, Ma. Ruth Langit",
  "DALAGAN-LOBO, Aiko Marie Estolano",
  "DAVID, Daniel Luis Abbariao",
  "DAVID, Jim John Lamsen",
  "DE CASTRO, Kirvin Lopez",
  "DE GUIA, Patrixia Joy Miclat",
  "DE JESUS, Michael Joseph",
  "DE LA CENA, Neil Omar Ricaplaza",
  "DE LEON, Alfred Justin Toledo",
  "DE LEON, Ivy Rose De La Torre",
  "DE RAMOS, Jamira Mercado",
  "DEL MUNDO, Loubelle Rejano",
  "DEL ROSARIO, Dexter Del Rosario",
  "DEL ROSARIO, Maria Bernadette Villanueva",
  "DELA CRUZ, Brian Bonifacio Manzanillo",
  "DELA CRUZ, Jahazielle Marie Ramos",
  "DELA CRUZ, Kim Arjay Sta. Maria",
  "DELA CUEVA, Jojee Rose Garcia",
  "DELIGERO, Jchelle Lustre",
  "DIAGRO, Mary Jane Fernandez",
  "DIAZ, Nathaniel Nolasco",
  "DILOY, Beanca Lontoc",
  "DIONISIO, Shianne Camille Villanueva",
  "DISTURA, Borgjie Bacelonia",
  "DOCTOR, Raymond Dominic Martinez",
  "DOMATOG, Mary Grace Pinangga",
  "DONATO, Geraldine Corre",
  "DOQUE, Blessie Capiendo",
  "DUMA, Aaron Elvis Javier",
  "DUMAYAS, Emmanuel Cezar",
  "DUNHAM, Katrina Aryap",
  "ENCINA, Jessica Alvar",
  "ENRIQUEZ, Mark Angelo Santos",
  "ESPERA, Jielene Kelly Evasco",
  "EVANGELISTA, Jan Jenny Lape",
  "FABON, Mary Angela Florentino",
  "FARIÑAS, Jessica Labucay",
  "FERNANDEZ JR., Nestor Tumampil",
  "FERRER, Johansen Zacarias",
  "FLORES, Noel Rodriguez",
  "FLORES, Rolirey Herico",
  "FORTUNO, Nikki Cantonjos",
  "FRADEJAS, Monchie Plata",
  "FRANCIA, Merryl Kristie Muro",
  "FRANCIA, Veronica Sigrid Brion",
  "FRANCISCO, Erlaine Faye Morales",
  "FRANCISCO, Jayson Alano",
  "FRANCISCO, Jose Rafael Miranda",
  "FRANCISCO, Mark Benedict Santiago",
  "FRONDA, Stephanie Carillo",
  "FURIGAY, Ralph Gino Pascua",
  "GABRILLO, Judith Lou Alvarado",
  "GACULA, Raya Risha",
  "GAL, Fatima Denise Tiamson",
  "GALANZA, Frances Ann Ilano",
  "GALVEZ, Juan Enrique Balilla",
  "GAMBOA, Argell Naranja",
  "GANTO, Sarah Rose Torres",
  "GARCIA-AZCUE, Kevin Michael Cruz",
  "GARCIA-JOCSON, Ivy Antivo",
  "GARGANTA, Lambert Yancy Burgos",
  "GARGOLES, Kimberly Galero",
  "GASCON, Chielo Antoniette Navasero",
  "GASPAN, Gabriel Sta. Ana",
  "GELVOSA, Sharmaine Buniel",
  "GIANAN, Ephraim De Quiros",
  "GIANAN, Yvette Dawn Primavera",
  "GIPAL, Wilmark Ombac",
  "GOLING, Honeyf Guro",
  "GOMEZ, Charliemayne Zulueta",
  "GONZALES, Cristina Marsado",
  "GONZALES, Dexter Lee Canlas",
  "GRANATIN, Jem Patricia Elauria",
  "GUEVARRA, Ma. Jessica Amurao",
  "GUSI, Audrey Rose Bersalona",
  "HERNANDEZ, Aizel Angelique Vizconde",
  "HINGAN, John Renan Galicia",
  "ILAGAN, Maria Martha Ysabel Durana",
  "ILANO, Farrah Fay Cadacio",
  "ILIGAN, Jan Rockefeller Cabrera",
  "INOCENTES, Raymond Justin Trogo",
  "JAINANI, Cush Ravin Espartero",
  "JALA, Sharisse Lara",
  "JUGAR, Christian John",
  "LABONITA, Ma. Kathryn Ogayon",
  "LAGASCA, James Ellis Ramos",
  "LAGGUI, Shane Irish Pagulayan",
  "LALU, Gianina Cheng",
  "LAPUZ, Iris Kristin Pulido",
  "LAVARIAS, Regina Purita Baldueza",
  "LAYUGAN, Chona Annogui",
  "LAZARO, Ivan Rei Sta. Ana",
  "LAZO, Rafael Jose Cortes",
  "LEAL-SANTOS, Reggie Jumauay",
  "LETADA, Ma Cassandra Gueta",
  "LICUANAN, Apple Jade Soriano",
  "LIGAY, Eunice Apolonio",
  "LIM, Lawrence Llyod Keh",
  "LIRA, Maria Theresa Cherrie Arcega",
  "LLIDO, Angelica Charme Tiongson",
  "LO, Ana Rosalie Barrameda",
  "LOJA, Stephanie Yarisantos",
  "LOOD, Jack Bagsican",
  "LUGUE, Harriete Cruz",
  "LUMAGUE-CERVANTES, Monica Villagracia",
  "MACABALLUG, Jessa May Tagapan",
  "MACABARE, Maria Akita Joy Cinco",
  "MACASINAG, Martin Xavier Tabuena",
  "MACASPAC-MARILIM, Stephanie Anne Magat",
  "MADRID, Denisse Kirstin Lourds Lingan",
  "MAGAMPON-OJANO, Ma. Jenice Sombon",
  "MALINGIN, Michael James Madrid",
  "MALTO, Maryknoll Nonato",
  "MANABAT, Ranulph Laxa",
  "MANAHAN, Kenneth Renzo Ricaforte",
  "MANAOG, Djamila Dawn Gonzaga",
  "MANGALUS, Geronimo Jr. Suba",
  "MANLANGIT-CASTILLO, Maria Elaine Espeso",
  "MANTILLA, Khristine Betancor",
  "MANUEL, Jan Miguel Talavera",
  "MANUEL, Ma. Milagros Millan",
  "MARASIGAN, Marie Loise Tabieros",
  "MARCELO, Mary Kate Clariz Ching",
  "MARIN, Rey-Ann Tusi",
  "MARQUEZ, Richcelyn Dimaranan",
  "MARTIN, January Pauline Ybañez",
  "MAYNIGO, Stanley Allen Kierulf",
  "MAÑEZ, John Michael Dizon",
  "MEDINA, Anthea Niña Batongbakal",
  "MEDIODIA, Carmel Ma. Tara Tan",
  "MENDIOLA, Luis Miguel Baluyot",
  "MENDOZA, Emiaj Francinne Manalo",
  "MENDOZA, John Maxwel Flores",
  "MENDOZA, Stephanie Rei Carreon",
  "MENESES, Raissa-Dee De La Paz",
  "MERCADER, Jeremy Marquez",
  "MIÑOZA, Danilo Jr. Persia",
  "MONILLA, Fritzie Domingo",
  "MONTEMAR, Joseph Ross Sta. Cruz",
  "MONTEMAYOR, Jesus Fernan Serafin",
  "MORILLO, Deniel Salvador Bentoy",
  "MORTEL, Azairah Booth",
  "NASALGA, Jose Marie Factorin",
  "NAVARRO, Lou Antonelle Dominguez",
  "NEPACINA, Karen Mae Cauilan",
  "NUENO, Cerwin Jan Delfin",
  "OBIAS, Michael Andrew Abustan",
  "OLFINDO, Joana Marie Tulio",
  "OLI, Julius Agustin",
  "OLIVAR, Rowena Gesulga",
  "OMAR, Midzfar Hamis",
  "ORTEGA, Justin Floro Francia",
  "ORTEGA, Kimberly Mickey Umali",
  "PADERNA, Francis Stephen Bonganay",
  "PADLAN, Shaunna Mae Simpao",
  "PAGADUAN-SANTOS, Remely Doral",
  "PAGARA, Ray Temporado",
  "PAJE, Gino Leocadio Saldajeno",
  "PALMIANO, Karen Jane Miguel",
  "PANGKAL, Shaima Eduria",
  "PARADO, Ma. Bettina Pascual",
  "PARAGAS, Fernando Villanueva",
  "PARAS, Irish Chiong",
  "PARAS, Maria Cristina Lourdes Alpapara",
  "PARAS-INOCENTES, Rhea Liza Joves",
  "PARWANI, Maria Abigail Abatayo",
  "PASCUAL, Joy Anne Creus",
  "PASCUAL, Samantha Keith",
  "PASTOR, Gee Agayam",
  "PATIÑO, Ross Anne Loneza",
  "PATRICIO, Patrick-Duane Villanueva",
  "PAVOREAL-GARCIA, Zarah Jane Sayco",
  "PEDERIO, Jennifer Louise Gonzaga",
  "PERALTA, Earl Kevin Herrera",
  "PEREZ, Kevin Gomez",
  "PEÑA, Adrian Jeric Garcia",
  "PEÑA, Roxanne Marie Garcia",
  "PILOTIN, Andrew Mark Reyes",
  "PINILI, Geoffrey Kyle Bisnon",
  "PINTO, Camille Bianca Rosario",
  "PISCASIO, Porsche Enriquez",
  "PUALENGCO, April Sarmiento",
  "PUNZALAN, Ma. Princess Mazell Demandante",
  "PY, Patrick Albino",
  "QUERIDO JR., Alexander Matias",
  "QUIETA, Mark Kevin Acevedo",
  "QUIZA, Justiniano Jr. Garcia",
  "RAGILES, Angelica Pascual",
  "RAMOS, Patricia Benilda Sta. Ana",
  "RANDE, Mohammad-Ali Usudan",
  "RECILLA, Ma. Lourdes Acosta",
  "RECTO, Loremer Pondevida",
  "REFORSADO, Arecar Arevalo",
  "REGALADO, Dustin Giron",
  "REGENCIA, Marie Anna Karla Madla",
  "REMALLA-MAYBITUIN, Bernadette Tangan",
  "REYES, Marie Sherrydane Co",
  "REYES, Mariecar Sunga",
  "REYES, Mariz Kristel Agodelo",
  "REYES-CABACUNGAN, Flor Marie Joy Yabes",
  "REYNOSO, Eric De Vera",
  "RICAFORT, Marie Victoria Borgonia",
  "RILLERA, Kathleen Rotoni",
  "RIVERA, Marlon Julita",
  "RIVERA, Reverie Joyce Formilleza",
  "RIVERA, Rhinnell Gomera",
  "ROA, Mary Rose Sy",
  "ROBLE, Juselle Tricia Sigales",
  "ROBLES, Windy Maralit",
  "ROMERO, Lea Steffi Gudes",
  "ROSALES, Andrew Ray Estrella",
  "ROSALES, Renzo Niño Mercado",
  "ROSARIO, Eurika Calinagan",
  "RUBI-ANITO, Pamela Samoramos",
  "RUIZ, Jevilyn Mary Canon",
  "SALAMERO, Jeremiah Talagtag",
  "SALIGAN, Constantine Araniador",
  "SALLES, Mariane Theresa Bergantin",
  "SAMPANG, Kristina Marie Olegario",
  "SAMSON, Kyla Mari Fernando",
  "SANCHEZ, Arch Pinili",
  "SANCHEZ, Michelle Mendoza",
  "SANDOVAL, Darren Robee Bayani",
  "SANIDAD, Jamyrah Cabalo",
  "SANTIAGO, Cheenee Rose Nuestro",
  "SANTILLAN, Mark Alfred Traqueña",
  "SANTOS, Bryan Mendoza",
  "SANTOS, Mike Ferdinand Zantua",
  "SANTOS, Mirasol Jamilla",
  "SARREAL, Joseph Vincent Bernard Balajadia",
  "SAVELLANO, Kristina Marie Sagmit",
  "SAY, Daniel Alexis Villar",
  "SEBRIO, Jan Gabriel Ledesma",
  "SEGUBIENSE JR., Renato Lotivio",
  "SENIN, Ruby Valles",
  "SIBAL, Maria Emilia Aveo",
  "SILVA, Marianne Elizabeth De Ocampo",
  "SILVESTRE, Marlon Albaña",
  "SINGZON, Marian Therese Samaniego",
  "SIRON, Juan Carlos Patawaran",
  "SORIANO, Manuel Alexander Orozco",
  "STO. TOMAS, Tim Julius Odiver",
  "SUBA, Paul Joshua Torda",
  "SUERO, Joselle Joy Abubo",
  "SUZUKI, Mariane Aquino",
  "TABABA-REYES, Ronee Javier",
  "TACUBOY-EXCONDE, Cris Angeli Villoria",
  "TAGLE, Kenneth Ray Bombita",
  "TAMAYO, Cheryl Cejalvo",
  "TANAY, Jodyne Liz Bautista",
  "TE, Mark Anthony Estanislao",
  "TEH, Kariz Elizabeth Amio",
  "TENERIFE, Coline Patricia Rivera",
  "TIANGCO, Rian Lee Binbin",
  "TIBERIO, Christelle Louie Cornillez",
  "TICA, Cristine Bernadette Capati",
  "TILA, Maria Christina Virginiza",
  "TIMOTEO, Aira Janille Adaoag",
  "TOLENTINO, Arleo Zoniko Cruz",
  "TOLENTINO, Faith Claire Jumalon",
  "TORIO, Christelle Ann Tuazon",
  "TORRENTE, Iris Gladys Llavan",
  "TORRES, Krisanto Maio Ramos",
  "TORRES, Melodie Concepcion",
  "TORRES III., Rodrigo Buenvivir",
  "TRINIDAD, Aura Mae Gonzales",
  "TRINIDAD, Mariane Joy Sagsagat",
  "TUBON, Lois Renee Ramos",
  "TULIAO, Marion Romina Bassig",
  "TUS, Ma. Ella Concepcion De Mateo",
  "VALDEZ, Lorrianne Nipal",
  "VALENCIA, Sidney Marie Vanessa Delgado",
  "VALENZUELA JR., Benigno Manuel",
  "VALENZUELA-BELGIRA, Hannah Tolosa",
  "VALMOCENA, Andrio Jerome Dumaguit",
  "VELANTE, Fernando Argana",
  "VELASCO, Sander Gener",
  "VELASQUEZ, James Macalanda",
  "VELOSO, Rafael Luis Miguel Navarro",
  "VILLAMOR, Jose Lorenzo Velasco",
  "VILLANUEVA, Christian Gelloagan",
  "WAMIL, Roderick Cacho",
  "YAN-CRUZ, Regine Lacson",
  "YARTE, Stephanie Lorraine Salva",
  "YASOL, Marry-Jean Videz",
  "YEPES JR., Leonardo Aguirre",
  "YU, Greg Winifredo Chua",
  "YU, Oliver William Ang",
  "ZARAGOZA, Yanna Feliza Baura",
  "ZOSA, Ericson Jed Sulla"
];

// Computed properties for reactive data
const sortedNames = computed(() => [...allNames].sort((a, b) => a.localeCompare(b)));

const divideIntoColumns = (list, columnCount) => {
  const columns = Array.from({ length: columnCount }, () => []);
  list.forEach((name, index) => {
    columns[index % columnCount].push(name);
  });
  return columns;
};

const columns = computed(() => divideIntoColumns(sortedNames.value, 3));
const maxRows = computed(() => Math.max(...columns.value.map(col => col.length)));
</script>