<template>
  <div class="relative overflow-x-auto py-8">
    <!-- Background Image -->
    <div class="absolute inset-0 z-0 flex items-center justify-center opacity-10">
      <img src="images/alflogo.png" alt="Logo" class="w-1/4 max-w-xs mx-auto" />
    </div>

    <!-- Table Content -->
    <div class="relative z-10">
      <table class="table-auto w-full max-w-7xl mx-auto border-collapse">
        <thead class="bg-official-purple-800 text-white">
          <tr>
            <th
              colspan="3"
              class="px-4 py-4 text-lg sm:text-xl md:text-2xl lg:text-3xl font-bold text-center uppercase tracking-wide"
            >
              The 2024 Bar Examinations Passers
            </th>
          </tr>
          <tr>
            <th
              colspan="3"
              class="px-4 py-4 text-lg sm:text-xl font-bold text-center bg-official-purple-700"
            >
              Hail to the 364 Arellano Lawyers!
            </th>
          </tr>
        </thead>
        <tbody class="divide-y divide-gray-200">
          <!-- Regular Passers in 3 Columns -->
          <tr v-for="(row, rowIndex) in maxRows" :key="rowIndex" class="flex flex-wrap md:table-row">
            <td
              v-for="(column, colIndex) in columns"
              :key="colIndex"
              class="w-full px-6 py-4 text-sm leading-6 text-gray-800 md:w-auto text-left md:text-left hover:bg-gray-50 transition-colors"
            >
              {{ column[rowIndex] || '' }}
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

<script setup>
import { ref, computed } from "vue";

// Full list of names for 2024 Bar Passers
const allNames = [
  "Abella, Chrysalina Ma. Harrieth Basa",
  "Abiog, Leandro Jose Jr. Gines",
  "Abitria, Joshua Emil Lontoc",
  "Acal, Rachel Andrelee Itchon",
  "Acero, Dan Emmanuel Ramirez",
  "Acosta, Ralph Reynan Fragante",
  "Aguila, John Louis Reyes",
  "Aguite, Graciel Agngaray",
  "Alambra, Michael Renz Requioma",
  "Aleman, Hector Dominic Dumelod",
  "Alfonso, Justinianne Joyce Guevarra",
  "Algarme, Danielle Kym Marie Real",
  "Allabo, Gabrielle Balbido",
  "Allapitan, Reyden Gregory Pangilinan",
  "Almeda, Keith Stephen Añes",
  "Almojuela-Ayo, Maria Anthonette Ramos",
  "Alviola, Emil Bugay",
  "Andales, Kent Wilson Orbase",
  "Andumang, Bernadeth Diaz",
  "Antiquiera, Eleonor Dumol",
  "Antonio, Christian Joseph Bathan",
  "Aquino, Alyssa Marcellano",
  "Aquino, Rafael Carlos Rafer",
  "Araneta, Marcie Denise Calimag",
  "Arrieta, Mary Irish Alve Ricacho",
  "Asilo, Kristin Joie De Jesus",
  "Auto, Jean Mary Ocampo",
  "Avellano, Desiree Buenaventura",
  "Badique, Dan William Bencito",
  "Bagay, Lemuel Victor Padpad",
  "Baguinon, Rald Gio Balatazat",
  "Balingit, Kimberly Clark Miguel",
  "Ballesteros, Andrew Paul Bathan",
  "Balmaceda, Jaelhen Rose Austria",
  "Barcena, Joanna Gracia Sarah Castro",
  "Baroma, Karl Michael Barbarin",
  "Bartolome, Hanna Karina Padilla",
  "Batcagan, Glenda Bension",
  "Bautista, Michael Lorenz De Jesus",
  "Bautista, Rey Matthew Carluen",
  "Belgira, Jessey Rexelle Mallapre",
  "Benzon, Maria Angela Sempio",
  "Bersamira, Anthony Kay Karl Par",
  "Biasca, Rajeen Jillian Del Valle",
  "Bilgera, Michael Del Rosario",
  "Biolena, Andrea Quinto",
  "Blanco, Deo Yonzon",
  "Blay, Jorelyn Reyes",
  "Bolos, Maria Gracia Patricia Santos",
  "Bongalonta-Reyes, Elizabeth Mae Balderama",
  "Bonifacio, Robert Urlanda",
  "Bringuelo, Jim Ryan Catungal",
  "Brinquez, Jovhilmar Estoque",
  "Buenviaje, Donna Liza Ciudad",
  "Busa, Jan Mark Balbaboco",
  "Cabasal, Mark Christian Castillo",
  "Cabbuag, Jaytrich Licayu",
  "Cachola, Carlos Miguel Garcia",
  "Caidlang, Denice Marck Estorninos",
  "Caldo, Catalino Jose Fabrao",
  "Cañete, Stephen Michael Ben",
  "Cariloria Cantos, Mary Myren Grace Festin",
  "Capuz, Ian Keith Nuñez",
  "Cariño-Pasquil, Katrina Evangelista",
  "Carsi Cruz, Alphonse Luiz Lleva",
  "Casimero, Airess Canoy",
  "Castañeda, Ramon Jose Vincenzo Lorenzo",
  "Castillano, Marmie Gil",
  "Castillo, John Radja Lipae",
  "Castro, Fidel Yngson",
  "Cauilan, Geni-Pearl Crystal Quay",
  "Chang, Bryant Symonds Bolor",
  "Cruz, Ella May Mailom",
  "Cruz, Joan Mae Ybañez",
  "Culangen, Bianca Lei Cortejos",
  "Cuna, Anna Christiana Suarez",
  "Cureg, Sylvan Ceazar Javier",
  "Curioso, Mikaela",
  "Custodio, Joshua Langit",
  "Cutaran, Jayson Gonayon",
  "Dacanay, Anne Marie Alexis Santillan",
  "Dacanay, Joshua Benjamin Tanglao",
  "David, Jhanine Valmocina",
  "Dayandante, Kenneth Velano",
  "De La Cruz, Elfa Faith Daquioag",
  "De Leon, Nathan Domingo",
  "De Los Reyes, Cesarah Roxanne Hayuhay",
  "De Roxas, Jhayrone Amurao",
  "De Vera, Gladys Climacosa",
  "De Vera, Jenica Jae Petras",
  "De Vera-David, Erikka Dayrit",
  "Del Mundo, John John Lapena",
  "Del Rosario, Abby Gail Galang",
  "Del Rosario, Alia Jacinta Coleen Andres",
  "Dela Cruz, Alyssa Claravall",
  "Dela Cruz, Arthur Jay Dela Fuente",
  "Dela Cruz, Jaylord Pastor",
  "Dela Cruz, Marvin Eric Operario",
  "Delgado, Jerchiel Wilfred Magcanam",
  "Diambulang, Roldan Mayo",
  "Diaz, Alexson Valeda",
  "Dimo, Al Savior Ramonal",
  "Diwa, Loren Marciana Bustos",
  "Dugayo, Jona Myka Quiopa",
  "Dulatas, Ruth Angela Honorio",
  "Dupo, Cheyanne Yveth Naval",
  "Eco, Mark Mallone Pablo",
  "Edusma, Rommel Rhino Catudio",
  "Empaynado, Andrea Mae Esusan",
  "Eniego-Belderol, Princess Pearl Bagares",
  "Enrile-Inton, Antonio III Alberto",
  "Enriquez, Esjay Sulangi",
  "Ersando, Christine Danielle Buenviaje",
  "Espina, Katrina Gemanil",
  "Espineda, Johnver X Ablao",
  "Espinoza, Patricia Rachelle Concepcion",
  "Espiritu, Stephen Andre Zapata",
  "Estenor, Nheslyn",
  "Eugenio, Beverly Mallillin",
  "Fadrilan, Kenneth Ferranco",
  "Fajanilan, Joven Apuya",
  "Fernandez, Anna Katrina Amaranto",
  "Fernandez, Jhonna Joy Villarubia",
  "Filio, Leira Marie Guevarra",
  "Filler-Taclas, Nicole Marie Candido",
  "Fortes, Glenn Guevarra",
  "Francisco, Angemeir Chloe Credo",
  "Fuentes, Flordeliz Aleste",
  "Gabriel, Jerommel Andres",
  "Galang, Gee Marie Gatuz",
  "Galang, Maria Avery Feliciano",
  "Galanza, Leonardo III Castrence",
  "Galapon, Jayson Agas",
  "Galias, Jessica Melle Lucero",
  "Galvez, Olidan Ceasar Cavada",
  "Gaño, Cheryl Pascua",
  "Garcia, Avien Rainell",
  "Garcia, Christiene Marella Alfonso",
  "Gasatan-Ong, Marieshem Laurel",
  "Gatinga, Gerald Mart Contreras",
  "Gawaran, Chester Paul Evangelista",
  "Generoso, Christine Ann Aceveda",
  "Genilo, Hanna Liia Patling",
  "Gernale, Paulo Miguel De Vera",
  "Gloton, Anna Melissa Teoco",
  "Go, Fred Michael Li",
  "Go, Jane Lizzette Rubis",
  "Go Ching, Marichar Devorah Cura",
  "Godalle, Krystine Joy Andricio",
  "Gongora, Patricia Kaye Tisbe",
  "Gonzales, Art Bryan Castel",
  "Gonzales, Jennica Alyssa Torno",
  "Guay, Elaine Grace Magaro",
  "Guballa, Althea Giulia Balgos",
  "Guimbal, Rhandel Colleen Balao",
  "Habana, Roselle Sorio",
  "Henson, Helen Nicolette Mercado",
  "Hernandez, Mariel Roxas",
  "Hiadan, James Carlo Frigillana",
  "Hizon, Patricia Nicole Buganan",
  "Honrado, Eillen Adrienne Lalwani",
  "Humilde, Helen Grace Malano",
  "Inovejas, Angelee Corpuz",
  "Ishihara, Rio Anne Azores",
  "Javier, Mac Vincent Esteban",
  "Jimenez, Christian Eligius Asuncion",
  "King, Jethro Aramis Varon",
  "Komoda, Akiko Tandoc",
  "Labajosa, Joseph Aaron Bolok",
  "Lado-Ing, Maria Anna Elizabeth Latayan",
  "Lagutan, Kenken Quimbo",
  "Lascoña, Ma. Lourdes Calunod",
  "Laverez, Ronie Bermejo",
  "Lecciones, Genirell Llagas",
  "Leguarda, Grace Batao",
  "Liban, Villi Marie Requezo",
  "Lindain, Jasemin Levardo",
  "Lomibao, Charlotte Anne Macavinta",
  "Lomibao, Vianca Antoniette Armas",
  "Lopez, Rhofel Torres",
  "Lozada, Gilbert Voltaire Ang",
  "Lucero, Micah Erica Salvador",
  "Macatangay, Odem Lali Agayo",
  "Magallon, Renelyn Ladesma",
  "Magararu, Lady Coleen Pamor",
  "Magbuhat, Marc Aaron Ganancial",
  "Magnaye, Gilbert Alcantara",
  "Malabanan, Nadine Macalalad",
  "Malazarte, Shim-B Gutierrez",
  "Malite, Rea Rosario General",
  "Mallare, Alyza Arra Suller",
  "Mallare, Justine Dunvy Medrano",
  "Mamaradlo, James Marvin Antigua",
  "Mananghaya, Elena Angela Javillonar",
  "Manguera, Gee Maurene Grepo",
  "Manimtim, Victoria Mae De Sagun",
  "Manio, Germiniano Jr. Dalisay",
  "Manuel, Andrea Elizze Quesada",
  "Manuel, Ralph Derek Villafranca",
  "Manzano, Gerie Rose Leal",
  "Marcos, Queenie Adriano",
  "Mariano, Ana Patricia",
  "Martinez Martin, Maria Faith Zamora",
  "Martinez, Pia Aila Dominguiano",
  "Mata, Gabrielle Jaye Villanueva",
  "Mateo, Jasper Arvin Rosete",
  "Mateo-Aquino, Naomi Pearl Rhea Mabuti",
  "Mayores, Erik Jean Alcaparaz",
  "Medina, Martynov Fuellas",
  "Mediodia, Ilssa Ma. Tara Tan",
  "Mendoza, Aran Khristian Aldaba",
  "Mendoza, Eller-Jed Mañalac",
  "Mendoza, Hazel Eliza Legaspi",
  "Menes, Patrick Bal Labo",
  "Merilles, Krishiena Gapas",
  "Miles, Chenie Erno",
  "Miranda, Christopher Aldwin Bucu",
  "Miranda, Jacqueline Portunes",
  "Miranda, Mikhail Isaac Lucas",
  "Monton, Alexis Marie Tabuquilde",
  "Mora, Noli Carbonell",
  "Morales, Nikka Mae Balacanao",
  "Muring, Glette-Yzak Dela Rosa",
  "Nacino, Allana Marie Punzalan",
  "Nagal, Niña Rivera",
  "Name, Angeli Amor Ramos",
  "Ng, Jeremiah Joseph Guevarra",
  "Noble, Rizalniño Lucido",
  "Noceda, Shiela May Militar",
  "Olmilla, Alyza Mariel Soriano",
  "Orcena, Janine Nicole Cuevas",
  "Orcullo, Ma. Danica Andeo",
  "Orcullo, Romavail Angelie Franza",
  "Ormita, Ellen Jane Llagas",
  "Orsolino-Petilos, Kris Pacrin",
  "Otadoy, Mary Chris Gingone",
  "Pacson, Timothy James De Leon",
  "Paguyo, Scarlet Nicole Fernandez",
  "Palos, Arcturus Viktor Ramirez",
  "Pampo, Ann Karen Faner",
  "Pancho, Edward Ocampo",
  "Panes, Dixie Amor Remerata",
  "Pangilinan, Veronica Sta. Rosa",
  "Pariñas, John Louie Matic",
  "Paulican, Donna Dominique Fugnit",
  "Payumo, Nicole Charlene Padilla",
  "Pe Benito, Lucky Egan Guntang",
  "Pecundo, Christian",
  "Peña Pelaco, Ana Katrina Langit",
  "Peñaverde-Ilarde, Cheryl Pediglorio",
  "Perania, Regine Joy Anas",
  "Perez, Francisco Palmeda",
  "Pila, Manilyn Trillianes",
  "Pineda, Jelyn Alyssandra Sibal",
  "Pinlac, Ma. Shannen Margarette Fontanilla",
  "Ponce, Edward John Jr. Carrillo",
  "Pulutan, Antoniette Asoy",
  "Punsalan, Renee Mariel Ong Sotto",
  "Quiambao, Leisaiah Yvonn Frialde",
  "Quiniquini, Neil Patrick Mendez",
  "Ramos, Jan Tristan Silva",
  "Rances, Christian Daza",
  "Ranoco, Albert John Abucot",
  "Rarama, Ramon Jireh Bacsa",
  "Ravanera, Justine Angelie Quezada",
  "Reandino, Steven Peach Llanos",
  "Reantillo, Gerard Angelo Garcia",
  "Red, Roi Earl Jacob",
  "Regala, Clarice Charlotte Tumblod",
  "Reyes, Aina Mikaela Oalog",
  "Reyes, Carmela Isabel Laplana",
  "Reyes, Mark Anthony Tanap",
  "Reyes, Michael Angelo Jr. Laplana",
  "Reyes, Michaella Bata",
  "Rigos, Ian Jasper Mendoza",
  "Riodeque, Lawrence Cui",
  "Rivera, Jean Pauline Salazar",
  "Robles, Danielle Denise Macatangay",
  "Roces, Ray Angelo Lodor",
  "Rodriguez, Marion Patricia Licup",
  "Rojas, Mark Genesis Alvarez",
  "Roma, April Anne Gaspan",
  "Ronda, Maria Danya Arinal",
  "Ronquillo, Kristoffer Flores",
  "Rosario, Ayla Ruth Flauta",
  "Rosario, Erika Rae Pinili",
  "Rosario, Louie Lim",
  "Rosete, Rowell Manuel",
  "Rozul, Joel Christian Gatpandan",
  "Sabillo, Jesah Lyne Lustado",
  "Sablaon, Arvin Joseph Alviar",
  "Sagun, Aldrich Joshua Resultay",
  "Salamat, Frela Gay Fojas",
  "Salazar, Christian Louie Bayugo",
  "Sales, Jazzerie Joy Mirasol",
  "Salomon, Charity Saria",
  "Salon, Maricel Cipriano",
  "Salonga, Charles Kevin Tiqui",
  "Salva, Chelsea Oliver",
  "Samaniego, Rosalou Kaye Loyola",
  "Sambuang, Pauline Anne Silayan",
  "Samin-Andres, Kazelwin Nicolas",
  "Samson, Camille Yasmeen Cruz",
  "Sanchez, Maria Leona Mendoza",
  "Sangalang, John Norbert Pedraja",
  "Sanguyu-Nam, Christy Maglalang",
  "Santosidad, Jonella Marie Borja",
  "Sapla, Genesis Jr. Baltazar",
  "Sarangay, Globertina Urenia",
  "Segismundo, Bea Rose Vigil",
  "Serrano, Christian Salcedo",
  "Serrano, Joseph Nicholas Ramirez",
  "Sison, Gellen Parreño",
  "Sobrenilla, Angela Luz Samaniego",
  "Soliman, Iana Alyssa Francisco",
  "Soriao, Jandell Chris Bernal",
  "Suller, Albert Bien Manalo",
  "Suwalawan-Hadjinoor, Jonaina Diamla",
  "Suyat, Duke Andrei Carandang",
  "Sy, Bryan Arabaca",
  "Sy, Exequiel Agustino",
  "Tan, Gabrielle David",
  "Tating-Tomanglao, Merian Joy Ogalesco",
  "Tawantawan, Nor-Aine Mamle",
  "Taypen, Angelo Magdalena",
  "Tejada, Mac Arthur Villanueva",
  "Tiaña, Jude Christopher Eborde",
  "Toledo, Jonathan Samuya",
  "Tolentino, Ivane Nathalie Lumat",
  "Tolentino, Karla Mae Canlas",
  "Tolentino, Pauline Anne Labata",
  "Tolentino, Vincent Maderazo",
  "Torino, Winston Mao Cortiguerra",
  "Torres-Gonzales, Lady Kris Punla",
  "Trillana, Jes Andre Guevarra",
  "Tuazon, Daniel Macalalag",
  "Tubog, Paolo Marco Antonio Perido",
  "Tumbali, Felix Bosi",
  "Ukol, Catalina Therese Lugtu",
  "Umali, Manuel Erven II Escasa",
  "Urbano, Chrystina Denise Cariño",
  "Valmonte, Shanen Valerie De Guzman",
  "Vasquez, Margreth Perez",
  "Velasco, Rod Paulo Mariñas",
  "Velasco-Julian, Deanne Kimberly Guison",
  "Velayo, Raezel Louise",
  "Ventura, James Ceasar Alejandro",
  "Vera, Ruth Ann Garcia",
  "Vergara, Khristine Joy Mary Carreon",
  "Vertulfo, Jeana Lyn Caceres",
  "Viaña-Villas, Monaliza Sanchez",
  "Victa, Carlos Emmanuel Abola",
  "Victoria, Dannah Fenellah Abasta",
  "Vidal, Miguel Lorenzo Morato",
  "Villanueva, Paolo Rint",
  "Villanueva, Reynald Aldrin Rosas",
  "Vinluan, Jose Antonio Tapia",
  "Volante, Ma. Isis Danielle Laluyan",
  "Wacnang, Hamilton Salimbay",
  "Wania, John Paul Badiola",
  "Yambao, Earl Justin Manuel",
  "Yanson, Johnela Malasique",
  "Zafe, Skyla Mae Lasala",
  "Zetha, Jadrin Edison Dizon"
];


// Function to capitalize last name
const capitalizeLastName = (fullName) => {
  const parts = fullName.split(",");
  if (parts.length < 2) return fullName;
  const lastName = parts[0].toUpperCase();        // capitalize last name
  const firstName = parts[1].trim();             // keep first name as-is
  return `${lastName}, ${firstName}`;
};

// Sorted and capitalized names
const sortedNames = computed(() =>
  [...allNames]
    .map(name => capitalizeLastName(name))
    .sort((a, b) => a.localeCompare(b))
);

// Divide into columns
const divideIntoColumns = (list, columnCount) => {
  const columns = Array.from({ length: columnCount }, () => []);
  list.forEach((name, index) => {
    columns[index % columnCount].push(name);
  });
  return columns;
};

const columns = computed(() => divideIntoColumns(sortedNames.value, 3));
const maxRows = computed(() => Math.max(...columns.value.map(col => col.length)));
</script>