<template>
  <div class="relative overflow-x-auto py-8">
    <!-- Background Image -->
    <div class="absolute inset-0 z-0 flex items-center justify-center opacity-10">
      <img src="images/alflogo.png" alt="Logo" class="w-1/4 max-w-xs mx-auto" />
    </div>

    <!-- Table Content -->
    <div class="relative z-10">
      <table class="table-auto w-full max-w-7xl mx-auto border-collapse">
        <thead class="bg-official-purple-800 text-white">
          <tr>
            <th
              colspan="3"
              class="px-4 py-4 text-lg sm:text-xl md:text-2xl lg:text-3xl font-bold text-center uppercase tracking-wide"
            >
              The 2025 Bar Examinations Passers
            </th>
          </tr>
          <tr>
            <th
              colspan="3"
              class="px-4 py-4 text-lg sm:text-xl font-bold text-center bg-official-purple-700"
            >
              Hail to the New Arellano Lawyers!
            </th>
          </tr>
        </thead>
        <tbody class="divide-y divide-gray-200">
          <!-- 19th Placer - Full Width Centered Row -->
          <tr class="bg-gradient-to-r from-blue-50 to-indigo-50">
            <td colspan="3" class="px-6 py-4 text-center border-b-2 border-blue-200">
              <div class="">
                <div class="text-2xl md:text-3xl font-bold text-blue-800">Allan Leo Tabuco Paran</div>
                <div class="text-lg font-semibold text-blue-600">11th Placer</div>
                <div class="text-sm text-blue-500 italic">(Examinees Who Obtained the Twenty Highest Ratings)</div>
              </div>
            </td>
          </tr>
          <tr class="bg-gradient-to-r from-blue-50 to-indigo-50">
            <td colspan="3" class="px-6 py-4 text-center border-b-2 border-blue-200">
              <div class="">
                <div class="text-2xl md:text-3xl font-bold text-blue-800">Randall Lipnica Pabilane</div>
                <div class="text-lg font-semibold text-blue-600">17th Placer</div>
                <div class="text-sm text-blue-500 italic">(Examinees Who Obtained the Twenty Highest Ratings)</div>
              </div>
            </td>
          </tr>

          <!-- The New Arellano Lawyers Header -->
          <tr class="bg-gradient-to-r from-purple-50 to-indigo-50">
            <td colspan="3" class="px-6 py-4 text-center">
              <div class="text-lg font-bold text-purple-800 uppercase tracking-wide">
                The New 513 Arellano Lawyers
              </div>
            </td>
          </tr>

          <!-- Regular Passers in 3 Columns -->
          <tr v-for="(row, rowIndex) in maxRows" :key="rowIndex" class="flex flex-wrap md:table-row">
            <td
              v-for="(column, colIndex) in columns"
              :key="colIndex"
              class="w-full px-6 py-3 text-sm leading-6 text-gray-800 md:w-auto text-left md:text-left hover:bg-gray-50 transition-colors"
            >
              {{ column[rowIndex] || '' }}
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

<script setup>
import { ref, computed } from "vue";

// Full list of names for 2025 Bar Passers (excluding the placer)
const allNames = [
  "ABELLA, Jaypee Niese",
  "ABENOJA, Phyllis Jessa Abenes",
  "ABRAZALDO, John Rabbi Igros",
  "ABROGUEÑA, Vaneza Sheryl Madroño",
  "ABUNDABAR, Jobyn Francis Sandoval",
  "ACEBUCHE, Adrian Cafe",
  "ACEVEDO, Javes Ronzon Jardenil",
  "ACLAN, Cassey Mae Derilo",
  "ADELINO, Mary Ann Santos",
  "AGNIR, Wenceslao IV Batoon",
  "AGUAS-JAVIER, Marjorie Joyce Balonzo",
  "AGUILA, Julia Verdan",
  "AGUILAR, Clyde Labis",
  "AL MAZROUIE, Jabber Mattar Mohammad Delgado",
  "ALCALA, Sofia Alysandra Halili",
  "ALCANTARA, Carl Matthew Reyes",
  "ALCANTARA, Hannah Raine Pangan",
  "ALEGRE, Gene Christian Benavidez",
  "ALFARO, Ann Margrette Pascua",
  "ALMIRA, Joshua Romeo Cruz",
  "ALVAREZ, Romdri Alindao",
  "AMANTE-BESAS, Jennelyn Angulo",
  "AMOROSO, Heather Marian Marquez",
  "AMPER-MANUEL, Christine Dobee Mercado",
  "AMSAN, Khristine Jade Labso",
  "AMURAO, Deanne Collen Mendoza",
  "ANDE, Royale Kaye Parica",
  "ANDRES, Kristine Ann Salas",
  "AÑONUEVO JR., Henry Lansangan",
  "ANYOG, Rona Graziela Pauline Bonayon",
  "AQUINO, Romart Dela Cruz",
  "ARADA, Ella Marie Acosta",
  "ARCELAO JR., Orlando Reyes",
  "ARGUMIDO JR., Salvador Velasco",
  "ASAN, Zukra Untikan",
  "ASI, Camille Beltran",
  "ASISTORES, Christan Lagua",
  "ASUNCION, Ma. Mae Vielle Gutierrez",
  "ASUNCION, Rogenil Jonathan Guillen",
  "ATIENZA, Sheryl Sanchez",
  "AUSTRIA, Jefferson Soterio",
  "AWID, Martin Angelo Padilla",
  "BABOL, Anabelle Cubangbang",
  "BACUD, John Ferdinand Parayno",
  "BALDEVIA, Marwin Agamon",
  "BALLARES, Joey Arandil",
  "BANACO, Ar-Ar Donato",
  "BANADERO, Andrea Mae Tolentino",
  "BANZUELA, Marp Vincel Jash Banayo",
  "BAQUIANO, Rosebee Lumbang",
  "BARACHINA, Kathleen Joy Bercilla",
  "BARBA, Daylinda Caducoy",
  "BARLAAN, Nicole Bernadette Mercado",
  "BARRAQUIAS, Betlee-John Tabobo",
  "BARTOLOME, Ceazar Leo Agorilla",
  "BATANGAN, Israel Dionisio",
  "BATARA, Richelle Mae Ramel",
  "BATOCTOY, Marvin Daryl Bertez",
  "BAUTISTA, Anthony Christopher Santos",
  "BAUTISTA, Arianne Mae Medina",
  "BAUTISTA, Rachel Anne Zarsuelo",
  "BEBANCO, Jovelyn Escorpion",
  "BELEN, Ray Lorenz Gawaran",
  "BELGIRA, Maria Catalina Bajar",
  "BERAMO, John Isaiah Formentos",
  "BIGALBAL, Geomari Dimalanta",
  "BOAQUIÑA, Mary Crischael Culala",
  "BOQUIREN, Inah Bianca Dulay",
  "BORDEOS-TE, Mary-Ann Cabiles",
  "BUCU, Jorland Marvin Hidalgo",
  "BUENAVISTA, Marianne Faye Ramírez",
  "BUENO, Geron Gabriel",
  "BUGAYONG, Marco Almario",
  "BUHAIN, Maria Monina Kaylee Fernandez",
  "BULAN, Kyanna Angela",
  "BUMANGLAG, Sarah Joy Torremillano",
  "BUMANGLAG, Niña Paula Asuncion",
  "BUNAG, Geselle Jean Calimlim",
  "BURCE, Emmanuelle Anne Mercado",
  "CABAÑERO, Giane Valerie Umale",
  "CABAÑEZAS, Vicente Deratas",
  "CABUNGCAL, Janela Bagadiong",
  "CAEZAR, Marc Julius II Cruz",
  "CAIRO, Richard Fabella",
  "CAJILIG, Edbal Josulp Mejorada",
  "CAJUCOM, Asher Bajeta",
  "CAJUDAY, Jemaruh Abias",
  "CALACALA, Emmille Rose Lectana",
  "CALADIAO, Claire Chelcee Reyes",
  "CAÑAVERAL, Cape Quesie Zerna",
  "CANONIZADO, Mae Lauren Morales",
  "CAPOQUIAN, Camille Joy Locop",
  "CAPULONG, Luis Raphael Marquez",
  "CAPULONG, Richard Quiambao",
  "CARDONA, Sean Alexander Mijares",
  "CARREON, Ma. Allen Rose Talavera",
  "CASANOVA, Mark Anthony Rosilio",
  "CASIDSID, Christine Deah Amar",
  "CASIÑO, Raphaelle Antoinette Rivera",
  "CASTILLO, Jheska Joyce",
  "CAVE, Allystair Louise Del Rosario",
  "CEZAR, Frederick Antonio",
  "CHUA, Kristy Anne",
  "CILLO, Esteban Jadocan",
  "CO, Kelly Irish Manantan",
  "CODIZAL, Juan Carlos Aquino",
  "COMIA, Harvey Sanmocte",
  "CONVOCAR, Jess Anne Demafiles",
  "CORTES, Brigette Gualvez",
  "COZ-ARCETA, Crizza Lyn Villanueva",
  "CRISTOBAL, Ayla Monicca Catalino",
  "CUASITO, Philline Vaje",
  "CUCIO, Angela Mae Dela Cruz",
  "CUENCA, Jeric Montes",
  "CUETO, Marinella Isabel Batiller",
  "CUEVAS, Maria Charina Laborte",
  "CUREG, Sean Jezer Javier",
  "DA JOSE, Joseph Andrei Pinion",
  "DANTE, John Marc Ruado",
  "DARIA, Maria Josefina Santiago",
  "DATUDACULA, Abdul Gaffor Datu-Haron",
  "DATU-IMAM, Rahandra Baser",
  "DAVID, Christine Joy Ongyor",
  "DAVID, Kyla Margarette Salvado",
  "DE ASIS, Maria Jessica Pagulayan",
  "DE GUZMAN, Araceli Marie Mauricio",
  "DE GUZMAN, Janella Egonia",
  "DE GUZMAN, Ma. Sybbles Paningbatan",
  "DE GUZMAN, Patricia Anne Coronado",
  "DE JESUS, Jan Anthony Albufera",
  "DE LA PEÑA, Jeanne Pauline Evaristo",
  "DE LEON, Emmanuel Catibog",
  "DE LEON, Jan Ysabel Uy",
  "DE LEON, Joshua Leonardo Reyes",
  "DE LEON, Ma. Angelica Bustos",
  "DE LUNA, Albert Olivay",
  "DE VERA, Vera Patricia De Leon",
  "DELA BAJAN JR., Danilo Pinto",
  "DELA CRUZ, Prince Klarenz Presincula",
  "DELA TORRE, Juan Rafael Carandang",
  "DELGADO, Antonio Tecson",
  "DEOCARIS, Nicole Anne Corpuz",
  "DEPASUCAT, Rommel Pedrajas",
  "DESENGAÑO, Argie Ortiz",
  "DIANO, Kenneth Arcibal",
  "DIAZ, Bono Kris Bermundo",
  "DIAZ, Felix Gerero",
  "DIAZ-LLAMAS, Pia Angelica Villagracia",
  "DILLERA, Robert Padilla",
  "DILOY, Genalyn Topacio",
  "DIMAAMPAO, Yasrima Rataban",
  "DIMALALUAN, Nancy Cabayao",
  "DIMAPILIS, John Philip Sanque",
  "DIMATATAC, Jan Therese Mojares",
  "DIMITUI, Daniel Ian Tuibeo",
  "DIONISIO, Melissa",
  "DOBLE, Keith Dimayuga",
  "DOMINGO, Marjumel Mina",
  "DUCUSIN, Amhina Mae Malicdem",
  "DULDULAO, Iana Deirdre Chavez",
  "DUMALIANG, Jaime Paulo Santos",
  "DUNAG, Mylene Liw-Agan",
  "DUYAO, Glenda Gay Bacuyag",
  "ECHANO, Patricia Angela Bugagao",
  "EMANO-PREGLO, Mimosa Diviena Sagrado",
  "ENRIQUEZ, Ricardo JR. German",
  "ERCE, Emuelson Sinigayan",
  "EREÑO, Elmer Saba",
  "ESBER, Anna Bianca Barlaan",
  "ESCARDA, Marc Farrell Tisbe",
  "ESGUERRA, Dana Elein Ilas",
  "ESGUERRA, Grace Casing",
  "ESPINOLA, Ma. Isabel",
  "ESTERIA, Marianne Angeline Sevilla",
  "EUGENIO, Regina Paula De Jesus",
  "EUGENIO, Ruzzel Palatino",
  "EVANGELISTA, Jellary Ungon",
  "FABREGAS, Allyssa Joy Español",
  "FABROS, Julian Paolo Tolentino",
  "FAJARDO, Maureen Samson",
  "FANDIÑOLA, Ciara Robyn Fernandez",
  "FERNANDEZ, Rianne Joy De Leon",
  "FERRER, Shirley-Marie Abugan",
  "FERRIOL, Michelle Ann Sanchez",
  "FLORES, Arvene Cacananta",
  "FORLALES, Paul Simon Lilang",
  "FRANCISCO, Axl Vinculado",
  "FRANCISCO, Eunice Jaurigue",
  "FRIAS, Selina Bianca De Leon",
  "FURIO, Michael Dizon",
  "GAERLAN, Joscel Ezra Lajo",
  "GALAGALA, Virginia Gutierrez",
  "GALANG, Kersie Quiambao",
  "GALE, Mary Louise Espinosa",
  "GALI, Roy Conrad Ricerra",
  "GALLA, Mark Lawrence Oriña",
  "GAMAD, Vincent Lorenz Yaptangco",
  "GAMBOA, Shayne Allen Antonio",
  "GAMBOA-GONZALES, Celine Lorielle Limpin",
  "GARCIA, Arianne Tutanes",
  "GARCIA, Juan Alfonso Montano",
  "GARCIA, Ma. Zandra Clindy Aliparo",
  "GARCIA, Pauline Bernadeth Dasal",
  "GAVAS, Anna Beatriz Martinito",
  "GELINDON, Gerry Gwaine Clemente",
  "GERELLA, Kristin April Carandang",
  "GERMINANDA, Prince Jhon Don III Mamugay",
  "GIBSON, Maria Regina Luancing",
  "GOICO, Earl Gerard Anthony Lopez",
  "GONZALES-PILAR, Janine Ma. Rilles",
  "GOZON, Maria Westphalia Bocobo",
  "GRAGEDA, Jannah Marie Tanduyan",
  "GRAPE, Michael Arvin Benjamin Soriano",
  "GRESOLA, Salvigrace Billones",
  "GUEVARRA, Alyssa Mae Francisco",
  "GUICO, Ramon Carlo Caronongan",
  "GUILING, Scandar Bryan Dator",
  "GUITERING, Jesel France Navarro",
  "GUIYAB, Pauline Karol Gabbuat",
  "GURO, Aga-Hamza Mulok",
  "HERNANDEZ, Adrian Baluyut",
  "HERNANDEZ, Fruzan Estimado",
  "HIPOLITO JR., Arturo Castro",
  "ICO, Honeylhet Dimasaka",
  "IGDANES, Jobeluz Ponte",
  "ILAGAN, Jeffrey Garcia",
  "ILOG, Irvin Henson Sta. Ana",
  "IRAN JR., Hugo Laurel",
  "ISIP, Iris Monique Montemayor",
  "JAMIG, Jericho Labay",
  "JESORO, Aaron Michail Basas",
  "JICKAIN, Luke Trono",
  "JIMENEZ, Mary Pauline Layson",
  "JOTA, Jessica Maca",
  "JOVELLANOS, Eunice Mari Panopio",
  "JOYA, Darby Janis Hernandez",
  "JUNIO, Jessica Mae Junio",
  "KIAMCO, Rommel Macachor",
  "KUA, Tracy Austin Ting Yu",
  "KUAN, Renniel Leslie Chua",
  "LABE, Mary Ann Crisostomo",
  "LAGUARDIA, Joanna Marie Luciano",
  "LAGUNILLA, Karl Davin Claros",
  "LAHOM, Sean Paolo Catalan",
  "LAPUZ, Marjunico Rifareal",
  "LARA, Arnette Apolonio",
  "LARGO, Nico Nambio",
  "LASALA, Angelo Sesbreño",
  "LAZARO, Anna Camille Pineda",
  "LAZARO, Aries Karlo Jude De Asis",
  "LAZARO, Clyde Richmond Bayos",
  "LAZARO, Joshua Kenneth Razo",
  "LEE, Loida Fruto",
  "LIM, Lanie Grace Santiago",
  "LIM, Michelle Brugada",
  "LINDO, Ma. Melissa Jamella Flores",
  "LITERAL, Juan Gabriel Monsalud",
  "LITUAÑAS, Marielle Erika Magbanua",
  "LIU, Therese Anne Lim",
  "LLANES, William Balasico",
  "LOCSIN, Nicole Alexis Mendoza",
  "LORO, Seifred Illao",
  "LOZADA, Dennise Endri Deysolong",
  "LUBO, Ferdinand Macapallag",
  "LUBO, Naldy Simbulan",
  "LUCENA, Jerrison Pierce Alhambra",
  "MABAN, Jimmy II Trazo",
  "MACARAYA, Hissah Sarangani",
  "MACOY, Allayza Claire Dominguez",
  "MACUGAY-TIOTUICO, Justine Villaver",
  "MADERSE, Angelica Gwen Rubio",
  "MADRID, Ma. Luisa Cashelle Pullon",
  "MAGBANUA, Ed Vincent Talban",
  "MAGHIRANG, Charmaine Perez",
  "MAGSAYSAY, Janine Louric Samonte",
  "MAINGAT, Trisha Alexis Ringor",
  "MALAB, Jan Mikki Daggao",
  "MALLARI, Mary Grace Montano",
  "MAMOYAC, Florencio III Arroyo",
  "MANANSALA, Charles William Vitug",
  "MANAOIS, Gene Osmon Bustos",
  "MANDONG, Sittie Haymah Tungcaling",
  "MANECLANG, Hay-C Azul",
  "MAÑEZ, Jose Miguel Agustin",
  "MANGACU, Bien Louis Manalo",
  "MANGALINDAN, Jona Phoebe Aguilar",
  "MANGUERA, Jade Ashley De Guzman",
  "MARCAIDA, Romina Angeliz Hofer",
  "MARCIA, Jesse Myl Angulo",
  "MARCOS, Eric Contillo",
  "MARIMLA, Jobert Christian Bondoc",
  "MARQUEZ, Ria Yzabela Gonzales",
  "MARTINEZ, James Ryan Monteverde",
  "MARTINEZ, Paolo Ray Mejica",
  "MASAOAY, Angelica Luisa Tagoon",
  "MASCARDO, Renz Marion Merabite",
  "MATITO, Zharina Fernandez",
  "MATSUDA, Michiko Viceral",
  "MAZO, Dustin Joseph Fetalino",
  "MEDALLA, Felinne Rose Guevarra",
  "MEDINA, Mary Elizabeth Baldevieso",
  "MENDIGUARIN, Tom Fernandez",
  "MENDOZA, Ethel Joi Manalac",
  "MENDOZA, Jhea Veronica Vijungco",
  "MENES, Nicole Reine Labo",
  "MENESES, Iluminado III De Castro",
  "MESINA, Elmar Bendicio",
  "MIAQUE, Elline Beatrix Lagumbay",
  "MIRANO, Veronica Cuento",
  "MISOLA, John Daedalus Pimentel",
  "MITMUG, Abdul Najib Bansao",
  "MOJICA, Robinson Simbajon",
  "MOLINO, Onilyn Mangoba",
  "MONCADA-ABELLA, Kareen Sarcia",
  "MONTANCES, Emmanuel",
  "MONTANTE, Milky Reataza",
  "MONTERA, Krisel Mendoza",
  "MORALES, Jay Daniel Torquator",
  "MOTAR, Regina Ara Majaba",
  "MOZO, Zoraya Lazaro",
  "NADAL, Corrine Mendoza",
  "NALDA, Ainna Rose Agravante",
  "NAÑADIEGO, Darien Anthony Fernandez",
  "NAVOA, Jasper Aldwin Manalo",
  "NESNIA, Aida Aranas",
  "NILLASCA, Paul Jason Balandra",
  "NOJARA, John Frederick Alivarvar",
  "NOMBREFIA-CAVIDA, Vivian Guerra",
  "NOVALES, Maryanne Therese Pescador",
  "OBMERGA, Sherrie Mieko Macam",
  "OCENAR, Ann Bernadette Marie Amis",
  "ODIÑA, Danisse Anne Mercado",
  "ODTUJAN, Kristine Jade Grumo",
  "OGAYON, Julienne Celine Gianan",
  "OLALIA, Myra Andrea Davalos",
  "ONEZA, Ma. Angelica Estadilla",
  "ONEZA, Ma. Denise Kathleen Estadilla",
  "ONGSIAKO, Patricia Realino",
  "ONOS, Abdul Rafi Maki",
  "ORTEGA, John Robert Morales",
  "ORTIZ, Xyza Paola Oblepias",
  "OSORIO, Katreena Andrea Sulayao",
  "PABILANE, Randall Lipnica",
  "PADERON, Joyce Anne Dayrit",
  "PADILLA, Clark Ian Sarmenta",
  "PAJARILLAGA, Jaynie Dela Peña",
  "PALISOC, Jimmy Mauricio",
  "PALOMAR, Lorna Eucogco",
  "PANTINO, Giancarlo",
  "PANUDA, Philip Graham Morales",
  "PARAN, Allan Leo Tabuco",
  "PARAS, Brian Jerald Estrella",
  "PARAS, Lorique Alexis Villanueva",
  "PAREDES, Sandra Lourdes Tablan",
  "PARIL, Farrah Fantastico",
  "PARIÑA, Ann Margarette Dimapilis",
  "PARIÑAS, Mikhaela Matic",
  "PARROCHA, Allan Dane De Vera",
  "PAYUMO, Kane Nielsen Mendoza",
  "PE, Gabriel John Gonzaga",
  "PELAEZ, Sharmaine Gutierrez",
  "PELAYO, Ranzel Szania Asilo",
  "PEÑA, Wyndee Grace Reynoso",
  "PEÑA, Therese Diana Ramoso",
  "PEÑAFLOR, Angeline Monique Ugale",
  "PEREZ, Gerard Paulo Corcega",
  "PEREZ-SONIDO, Grace Pastoral",
  "PINEDA, Maria Elena Tariman",
  "PINNOCK, Jennifer Trinidad",
  "PO, Michael Kenneth Ignacio",
  "POLICAR, Den-Marcus Lee",
  "PONCE, Maria Veronica Castro",
  "PORCIUNCULA, Jehoverey Dancel",
  "PRANES, Jona Boglosa",
  "PULTA, Carisse Sarguilla",
  "PUNO, Ricardo Marpuri",
  "PURUGGANAN, Ralph Janssen",
  "QUE, Jamieline Tamondong",
  "QUE, Jarred Noelan Barra",
  "QUELNAN, Mark Jose Cadigoy",
  "QUIAMCO, Jhade Cudiamat",
  "QUILIT, Rose Maylyn Ramos",
  "QUIMING, Paolo Angelo De Vera",
  "QUINCE, Sarah Jane Libao",
  "RABINO, Krizelle Dinlasan",
  "RACELA, Mel Geomari Francisco",
  "RAMIREZ, Sean Andre",
  "RAMIREZ, Kristal Mae Padilla",
  "RAMOS, Kamille Loise Asis",
  "RAMOS, Maureen Navales",
  "RAPINAN, Kamille Mae Basco",
  "RATERTA, Zandrina Ann Fainza",
  "RAVANILLA, Imari Joie Ladesma",
  "RECOMENDABLE, Eric Marbid",
  "RED-EBUENGA, Gloria Macapagal",
  "REDITO, Cherrie Ocan",
  "REGENCIA, Christiana Faye Tabada",
  "REGLO, Jane Cabaluna",
  "RENDON, Anne Margaret Alday",
  "REYES, Brent Simoun Ballon",
  "REYES, Kristelle Leigh Aurigue",
  "REYES, Ma. Patricia Nicole Gutierrez",
  "REYES, William Charles Rima",
  "RIALP, Jerlo Kevin Pasamba",
  "RITO, Christian Paul Mendenilla",
  "ROCAFOR, Bonier Verano",
  "RODIL, King Paul Vincent",
  "RODRIGUEZ, Juan Carlos Ventura",
  "ROJAS, Eddie II Jaya",
  "RONQUILLO, Kurt Raniel Dominic Estrada",
  "ROQUE, Gio Vincent Bernasor",
  "ROQUE, Tristan Troy Velasquez",
  "ROSALES-FIDEL, Angela Sharmaine Atienza",
  "ROSARIO, Mary Antonette Caponpon",
  "ROYO, Diane Rutor",
  "SABANDO, Mary Denielle Valeriano",
  "SALCEDO, Sofia Patricia Luga",
  "SALUYA, Jason Felix",
  "SALVACION, Nhorway Lapasanda",
  "SALVADOR, Gehannah Rie Therese Sazon",
  "SALVADOR, Thalia Rose Ann",
  "SAN JOSE, Naomi Tolentino",
  "SANCHEZ, Oliver Tapia",
  "SANDOVAL, Fritz Marion Palma",
  "SANTOS, Carlo Diego",
  "SANTOS, Jesher Mark Valdez",
  "SANTOS, Riza Aganon",
  "SARMIENTO-SAPAULA, Marianne Balane",
  "SEBASTIAN, Joshua Allen Benipayo",
  "SECRETO, Joanne Mae Reyes",
  "SEMETARA, Ma. Richelle Gacosta",
  "SEÑORES, Mary Louis Ardamil",
  "SERVAÑEZ, Romalyn Esparrago",
  "SEVA, Felipe Jr. Bilo",
  "SIAYNGCO, Zachary Pacino Valdez",
  "SIM, Zer Min Blances",
  "SINON-DELA ROSA, Kathleen Gallena",
  "SINSON, Angelo John Lachica",
  "SIPIN, Pauline Eunice Cabatu",
  "SISA, Anna Mae Trinidad",
  "SOLANO, Angelo Tortuya",
  "SOLANO, Toni Joy Apaling",
  "SOLAS, Loren Christine Soberano",
  "SUDARIO, Rena Geraldo",
  "SULIT, Alexis Angelo Lomotac",
  "SUMBILLO-CHANG, Maricris Pacia",
  "SURESCA, Dyan Corpuz",
  "SUWALAWAN-BALT, Jolina Diamla",
  "SUYAT, Gian Jeruie Fajardo",
  "TABOR, Samantha Nicole Llido",
  "TABUNAN, Khristine Joan Bata",
  "TACCAD-DIZON, Atheena Santos",
  "TALAPIAN, Mary Shane Apostol",
  "TALENS, Alyssa Joira Carganilla",
  "TALLA, Alan Jay Ortiz",
  "TAMACAY, Roderick Felimon",
  "TAMPICO, Eldene Llono",
  "TAN, Faye Louise Cordovez",
  "TAN, Gerard Chua",
  "TAN, Princess Edith Arcega",
  "TANJUTCO, Fatima Grace Ocampo",
  "TATLONGHARI, Trisha Lourds Malabanan",
  "TAYLAN, Aira Dyanne Sales",
  "TE, Sherwind Mon Pascual",
  "TEE, Aaron Lester Sales",
  "TENA, Patricia Celine Bagarino",
  "TERNORA, Kathlyn Baculi",
  "TERTE, Karen Alvaran",
  "TESORERO, Suzainne Sioco",
  "TIBAYAN, Noel Salvacion",
  "TIGNO, Rafaela Marie Reyes",
  "TIRONES, Renee Rose Dino",
  "TOLEDO, Royce Harvey Amutan",
  "TOLIBAS, Peter Ginio Nicolas Paraguya",
  "TORIO, Mark Joseph Fernando",
  "TRIMOR, Cyx Lloyd Dela Peña",
  "TUAÑA, Ace Justin Ced",
  "UBALDE, Geelleanne Laxamana",
  "UNGRIA, Frances Elise Arcilla",
  "UNTALAN, Ren Prescill Marasigan",
  "URGEL, Hazelle Charisse",
  "USERO, John Steven Delos Santos",
  "UY, Ferdinand Galad",
  "VALDEZ, Dominador JR. Rabena",
  "VALDEZ, Suzette Pascual",
  "VALENZUELA, Arnold Ponce",
  "VASQUEZ, Gilbert Santiago",
  "VENTURINA, Therese Rachelle Mamaoag",
  "VERDADERO, Benjamin Luke Phillip Genete",
  "VERGARA, Johaina Micah Guce",
  "VERGARA, Therese Mary Anne Zalameda",
  "VERZOSA-NOCHE, Emerald Alayza",
  "VIBAL, Joan Karla Garcia",
  "VILLALVA, Cristina Miguela Villamala",
  "VILLAMIL, Mary Nicole Miranda",
  "VILLANUEVA, Al Glejan Juacalla",
  "VILLANUEVA, Erico Gutierrez",
  "VILLANUEVA, John Fiel Dueñas",
  "VILLANUEVA, Nelson Clyde Labaclado",
  "VILLAR, John Ezra Gamboa",
  "VILLAR, Lester John Acaja",
  "VILLASTIQUI, Kohl Moses Macagba",
  "VILLEGAS, Veronica Tallera",
  "VILLON, Ana Lauren Kei Filardo",
  "VINCULADO, Christian Patrick Estarez",
  "VIRGINO, Clarisse Yvette Pagtananan",
  "VISDA, Isabella Panlaqui",
  "YOUNG, Albert III Obrador",
  "ZABALLA, Samantha Granatin",
  "ZAYAT, Kimvirly Pre",
];


// Computed properties for reactive data
const sortedNames = computed(() => [...allNames].sort((a, b) => a.localeCompare(b)));

const divideIntoColumns = (list, columnCount) => {
  const columns = Array.from({ length: columnCount }, () => []);
  list.forEach((name, index) => {
    columns[index % columnCount].push(name);
  });
  return columns;
};

const columns = computed(() => divideIntoColumns(sortedNames.value, 3));
const maxRows = computed(() => Math.max(...columns.value.map(col => col.length)));
</script>